### ISSUE TITLE
Tests Fail

### ISSUE THREAD

**Issue by patricksnape** [tf-coreml/tf-coreml#101]
# Environment
Python 2
OSX

From inside tf-coreml root folder:

`pip install -e .`
`pytest tests`

branch: master afec1447de6de0db05832a522ccff64b4fac4991

# Encountered Issue
`AssertionError: Output feature cannot be a placeholder`

Is being thrown on most tests

**Comment by aseemw** [comment]
I have not been able to reproduce this error.
Can you try running individual tests and see which tests give such an error. You can run individual tests by doing something like this:
`pytest test_tf_converter.py::TFSimpleNetworkTest::test_toy`

**Comment by patricksnape** [comment]
Apologies, my environment was dirty and Pytest was invoking Python 3. This is fixed by:

#125

And this can be closed as incorrectly reported.
