### ISSUE TITLE
Build fails on unsupported Ops

### ISSUE THREAD

**Issue by iCappsCedric** [tf-coreml/tf-coreml#104]
I am trying to use your converter to make my .pb model into a .mlmodel

In my convertor.py I have the following
`import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'retrained_graph.pb',
                     mlmodel_path = 'mymodel.mlmodel',
                     output_feature_names = ['final_result:0'])`

When trying to build this, I get the following error: 

>   File "convertor.py", line 4, in <module>
    output_feature_names = ['final_result:0'])
  File "/Users/xxxx/Documents/NewTry/retrainedversion/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 477, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "/Users/xxxx/Documents/NewTry/retrainedversion/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 143, in _convert_pb_to_mlmodel
    _check_unsupported_ops(OPS, output_feature_names)
  File "/Users/xxxx/Documents/NewTry/retrainedversion/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 111, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported Ops of type: DecodeJpeg

I feel like it's an issue in your code. I've followed numerous tutorials on this (including: https://hackernoon.com/integrating-tensorflow-model-in-an-ios-app-cecf30b9068d) and it still fails.

**Comment by nivim** [comment]
from the - 

> Unsupported Ops of type: DecodeJpeg

I'm assuming you are trying to use the Inception_v3 model.
The DecodeJpeg layers should be removed for the MLModel.
There is an example in the examples folder specially for it (inception_v3).

**Comment by iCappsCedric** [comment]
I tried running from your example
`import tensorflow as tf
# Load the TF graph definition
tf_model_path = './retrained_graph.pb'
with open(tf_model_path, 'rb') as f:
    serialized = f.read()
tf.reset_default_graph()
original_gdef = tf.GraphDef()
original_gdef.ParseFromString(serialized)

# For demonstration purpose we show the first 15 ops the TF model
with tf.Graph().as_default() as g:
    tf.import_graph_def(original_gdef, name='')
    ops = g.get_operations()
    for i in xrange(15):
        print('op id {} : op name: {}, op type: "{}"'.format(str(i),ops[i].name, ops[i].type));

# Strip the JPEG decoder and preprocessing part of TF model
# In this model, the actual op that feeds pre-processed image into
# the network is 'Mul'. The op that generates probabilities per
# class is 'softmax/logits'
# To figure out what are inputs/outputs for your own model
# You can use use TensorFlow's summarize_graph or TensorBoard
# Visualization tool for your own models.

from tensorflow.python.tools import strip_unused_lib
from tensorflow.python.framework import dtypes
from tensorflow.python.platform import gfile
input_node_names = ['final_training_ops/Wx_plus_b/add']
output_node_names = ['final_result']
input_graph_def = ['']
gdef = strip_unused_lib.strip_unused(
        input_graph_def = original_gdef,
        input_node_names = input_node_names,
        output_node_names = output_node_names,
        placeholder_type_enum = dtypes.float32.as_datatype_enum)
# Save it to an output file
frozen_model_file = './inception_v3.pb'
with gfile.GFile(frozen_model_file, "wb") as f:
    f.write(gdef.SerializeToString())
`
now my 87mb file became 134 bytes, but the script did not show any errors. Still I feel this is very wrong since it's only 134 bytes. Any recommendations?

**Comment by szemian** [comment]
Assuming you were retraining the model following the steps of "Tensorflow for Poets 2", the **input_node_names** should be **['Mul']**, at least that was my case and I have successfully convert the model for core ml.

**Comment by aseemw** [comment]
Closing now. Can be opened when there is more information.
