### ISSUE TITLE
How to convert model with 2 input parameters?

### ISSUE THREAD

**Issue by czater** [tf-coreml/tf-coreml#106]
Hello,

I am trying to convert model with 2 input parameter - int and image. For now I am getting something like this:
`Core ML input(s): 
 [name: "style_num__0"
shortDescription: "This input is a sequence of length 26"
type {
  imageType {
    width: 1
    height: 1
    colorSpace: GRAYSCALE
  }
}
, name: "input__0"
type {
  imageType {
    width: 1000
    height: 1000
    colorSpace: RGB
  }
}
]
Core ML output(s): 
 [name: "Squeeze__0"
type {
  multiArrayType {
    dataType: DOUBLE
  }
}
]`

after doing that:
`import tfcoreml

tfcoreml.convert('styl.pb', 
                 mlmodel_path="stylize3.mlmodel", 
                 input_name_shape_dict={"input:0":[1,1000,1000,3]}, 
                 output_feature_names=["Squeeze:0"], 
                 image_input_names= ["input:0", "style_num:0"])`

**Comment by czater** [comment]
Anyone?

**Comment by aseemw** [comment]
In this [unittest](https://github.com/tf-coreml/tf-coreml/blob/39d3ade647d21d72c6851b7822dbd2252442203e/tests/test_pretrained_models.py#L505) there is an example of converting a model with two inputs (an image and a length 26 one-hot vector to choose the style). Does that answer you question?

**Comment by czater** [comment]
It's give me almost the same result :/ Is there anyway to have int instead of MLMultiarray for choose style?

**Comment by czater** [comment]
Well it's still gray image :/ Do I need to use some weights for this?

**Comment by aseemw** [comment]
Are you using [this](https://storage.googleapis.com/download.tensorflow.org/models/stylize_v1.zip) model or some other model?

**Comment by czater** [comment]
yep, this model that I am using
