### ISSUE TITLE
tensorflow to coreml max() arg is an empty sequence

### ISSUE THREAD

**Issue by dhananjaykumardubey** [tf-coreml/tf-coreml#114]
Hi All,

I am beginner to neural networks and I just started to learn tensorflow from tutorials, and while converting the .pb model to mlmodel , I m getting the following error:

/anaconda2/lib/python2.7/site-packages/coremltools/models/_feature_management.py", line 295, in process_or_validate_features
    num_dimensions = 1 + max(chain(*[il for k, il in features.items()]))
ValueError: max() arg is an empty sequence.

This is the code I am following to convert:

import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'image.pb',
                     mlmodel_path = 'myFirstImageModel.mlmodel',
                     output_feature_names = ['Softmax_2:0'])

Can you guys please help me out here.

Thanks

**Comment by aseemw** [comment]
Hi dhananjaykumardubey, could you provide a bit more info about the image.pb model that you are trying to convert? If it is a model you downloaded From somewhere it would be useful if you could share the link and I can try reproducing the error you are getting locally.

**Comment by dhananjaykumardubey** [comment]
Hi Asee,
Hope you doing good. I used flickrLogoDataSet, and trained that data set into model. I received 4 files under models folder named - checkpoint, logo_model.data, logo_model.index & logo_model.meta. Then I used freeze_graph.py , please find the code below:

import tensorflow as tf
from tensorflow.python.framework import graph_util
import os,sys

output_node_names = "Softmax_2"
saver = tf.train.import_meta_graph('models/logo_model.meta', clear_devices=True)

graph = tf.get_default_graph()
input_graph_def = graph.as_graph_def()
sess = tf.Session()
save_path = "models/logo_model"
saver.restore(sess, save_path)
output_graph_def = graph_util.convert_variables_to_constants(
            sess, # The session is used to retrieve the weights
            input_graph_def, # The graph_def is used to retrieve the nodes 
            output_node_names.split(",") # The output node names are used to select the usefull nodes
) 
output_graph="image.pb"
with tf.gfile.GFile(output_graph, "wb") as f:
    f.write(output_graph_def.SerializeToString())
sess.close()


And this resulted me into .pb file, which I am trying to convert into coreml. 

Hope this helps.

**Comment by aseemw** [comment]
Actually what is needed to debug is the actual model architecture. If possible can you provide the download link to the .pb file (with random weights maybe) or provide the python code where you describe the model architecture, that would be useful.

**Comment by dhananjaykumardubey** [comment]
I was following this git repo, by  "satojkovic". 
https://github.com/satojkovic/DeepLogo
If this helps. 

Also, I tried using tf-coreml/examples/inception_v3.ipynb , and was getting this error

Caused by op u'add_14', defined at:
  File "strip_model.py", line 54, in <module>
    image_input_names = ['MatMul_5:0'])
  File "/Users/dhananjaykumardubey/anaconda2/lib/python2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 478, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "/Users/dhananjaykumardubey/anaconda2/lib/python2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 138, in _convert_pb_to_mlmodel
    tf.import_graph_def(gdef, name='')
  File "/Users/dhananjaykumardubey/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "/Users/dhananjaykumardubey/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/Users/dhananjaykumardubey/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [1,299,299,3] vs. [28]
	 [[Node: add_14 = Add[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_MatMul_5_0_0, Variable_4)]]

**Comment by aseemw** [comment]
The model you linked here does not have a Placeholder op. A placeholder op is required to specify the input of the model. 

Here is what I did. I downloaded the model and used Graph transform [tool](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md) to convert it into a model with a placeholder. 

Here is the script I used for that (after building the TF graph transform tool):
tensorflow/bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=deepLogo.pb \
--out_graph=modified_deepLogo.pb \
--inputs='Const_6' \
--outputs='Softmax_2' \
--transforms='
strip_unused_nodes(type=float, shape="1,32,64,3")
'

I was then able to convert the model to CoreML.

tfcoreml.convert(
        tf_model_path = 'modified_deepLogo.pb',
        mlmodel_path = 'modified_deepLogo.mlmodel',
        output_feature_names = ['Softmax_2:0'],
        input_name_shape_dict = {'Const_6:0':[1,32,64,3]})

**Comment by dhananjaykumardubey** [comment]
Hi Aseem, Thanks for helping me out. But now I am struggling with getting transfor_graph. I installed tensorflow without sourcecode, and I can't find this tool in my tensorflow directory. 
If I go with building my pip_package installation fails . I think the reason being of failure is CUDA toolkit, I've macbook pro, which doesn't have NVIDIA GPU by default. So, CUDA is not supporting may be. So, do I have any option to run the above script without installing tensorflow from source?

**Comment by aseemw** [comment]
To build graph transform tool:
- clone tensorflow repo
- execute command "./configure" from the root directory
- it will ask a bunch of questions, most of them you could say no (when it asks about enabling CUDA)
- after that you can execute the script to build the graph transform tool, which is "bazel build tensorflow/tools/graph_transforms:transform_graph"

**Comment by dhananjaykumardubey** [comment]
Thanks a lot @aseemw . It was really helpful and learning for me. 👍
