### ISSUE TITLE
Output feature cannot be a placeholder

### ISSUE THREAD

**Issue by tgwagner** [tf-coreml/tf-coreml#117]
Hi there,

I'm running the following script and receive an "**output feature cannot be a placeholder error**" (tfcoreml/_tf_coreml_converter.py line 175)

error:

> Traceback (most recent call last):
>   File "converttest2.py", line 6, in <module>
>     image_input_names = ['input:0'])
>   File "/Users/tgwagner/fresh/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 483, in convert
>     predicted_probabilities_output=predicted_probabilities_output)
>   File "/Users/tgwagner/fresh/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 175, in _convert_pb_to_mlmodel
>     ('Output feature cannot be a placeholder')
> AssertionError: Output feature cannot be a placeholder
> 

Script is:
```
import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = '/users/fresh/darkflow/built_graph/tiny-yolo-NFPA.pb',
                     mlmodel_path = 'my_model.mlmodel',
                     output_feature_names = ['output:0'],
                     input_name_shape_dict = {'input:0':[1, 416, 416, 3]},
                     image_input_names = ['input:0'])

```

I summarized my model using summarize_graph (from tensorflow tools) with the following output:

> =/users/tgwagner/fresh/darkflow/built_graph/tiny-yolo-NFPA.pb
> Found 1 possible inputs: (name=input, type=float(1), shape=[?,416,416,3]) 
> No variables spotted.
> Found 1 possible outputs: (name=output, op=Identity) 
> Found 15770590 (15.77M) const parameters, 0 (0) variable parameters, and 0 control_edges
> Op types used: 59 Const, 16 Mul, 9 Conv2D, 9 BiasAdd, 9 Pad, 8 Sub, 8 Maximum, 8 RealDiv, 6 MaxPool, 1 Placeholder, 1 Identity, 1 NoOp
> 

what am I missing?  This is a model derived from tiny_yolo_voc.cfg 

Thanks

**Comment by aseemw** [comment]
Hi can you print a text summary of the graph using the script "utils/inspect_pb.py" and check whether the output name of the op of type "Placeholder" is "output:0" or not. Or more specifically, which op emits the "output:0" tensor.

**Comment by patricksnape** [comment]
Apologies, my environment was dirty and Pytest was invoking Python 3. This is fixed by:

https://github.com/tf-coreml/tf-coreml/pull/125

**Comment by aseemw** [comment]
Closing now. Can be opened when there is more information.
