### ISSUE TITLE
Possibility to add implementations for unknown layers

### ISSUE THREAD

**Issue by mats-claassen** [tf-coreml/tf-coreml#120]
Hi, what do you think of the idea of having a parameter in the `convert` function were the user can pass a function that handles potential unsupported layers?

What I have in mind is something like [torch2coreml](https://github.com/prisma-ai/torch2coreml) has with the `unknown_layer_converter_fn` parameter.

**Comment by aseemw** [comment]
Just to understand it correctly, the "unknown_layer_converter_fn" allows to insert custom layers in the CoreML graph, right? 

Yes, a flag along the lines of the "add_custom_layers" Flag, as in the coremltools Keras converter, would be added.

**Comment by mats-claassen** [comment]
Actually I think there are two types of unknown layers. First, the one you mention which tackles those layers that CoreML does not support so that they have to be implemented in Swift. The other is for those layers that tf-coreml doesn't support, i.e. does not convert to CoreML. I think both cases would be helpful.

**Comment by aseemw** [comment]
PR #179 adds the ability to add custom layer proto messages during conversion.
