### ISSUE TITLE
About ssd_examples

### ISSUE THREAD

**Issue by hbfreedow** [tf-coreml/tf-coreml#121]
Hi, I use [ssd_mobilenet_v1_coco.config](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_coco.config) to train my own dataset, and I finally get .pb file, however, when I call convert as blow step:
coreml_model = tfcoreml.convert(
        tf_model_path=frozen_model_file,
        mlmodel_path=coreml_model_file,
        input_name_shape_dict=input_tensor_shapes,
        output_feature_names=output_tensor_names)
but the output is not the same as [.pb](https://storage.googleapis.com/download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_android_export.zip), so, how can I get the same .pb file as google? thx

**Comment by aseemw** [comment]
Hi @hbfreedow, we would need a few details to debug your issue. For instance, which network (.pb) exactly are you converting and what is the output tensor blob that you are comparing. And how different are the outputs from coreml and TF ?

You might also want to take a look at this thread for converting the SSD model: https://github.com/tf-coreml/tf-coreml/issues/107
and the repo: https://github.com/vonholst/SSDMobileNet_CoreML

**Comment by aseemw** [comment]
Closing now. Can be opened when there is more information.
