### ISSUE TITLE
Support for python3

### ISSUE THREAD

**Issue by mliesenberg** [tf-coreml/tf-coreml#123]
with `coremltools` available for python 3 via pypi now, is it planned to release `tf-coreml` for python 3 as well?
happy to chip in, if needed.

**Comment by aseemw** [comment]
Yes that is a good point! I have made a note. 

Sure, we'll be happy to get your help! If you want, you can start a PR that we can jointly contribute.

**Comment by mliesenberg** [comment]
ok, I'll start by running `2to3` and then we can take it from there. Not sure about your conventions etc.

**Comment by patricksnape** [comment]
See https://github.com/tf-coreml/tf-coreml/pull/125

**Comment by aseemw** [comment]
#125 is merged. Great job @patricksnape !!
