### ISSUE TITLE
ValueError: Graph has cycles.

### ISSUE THREAD

**Issue by MatthewWaller** [tf-coreml/tf-coreml#124]
Hello, and thank you so much for this huge undertaking! I'm working on trying to convert Mozilla's DeepSpeech pre-trained model, and I get the error: "ValueError: Graph has cycles."

Any ideas about what I could do for this? Are graphs with cycles simply not going to work?

**Comment by aseemw** [comment]
CoreML does not support graphs with cycles at the moment. However, it does support recurrent nodes (RNN, LSTM, GRU etc). When these cells are implemented in TF, they get broken down into cyclic graphs in the frozen .pb file. tfcoreml cannot handle such graphs at the moment. This is a known issue currently. Handling such graphs would require going from the broken down graph structure to the higher level structure and mapping the nodes to an operation that CoreML supports (RNN, LSTM etc). 

I think the simplest way for to deal with such graphs now, is to abstract the weight matrices and bias vectors. And then use them to build a CoreML model directly using the neural network builder [API](https://apple.github.io/coremltools/generated/coremltools.models.neural_network.html) provided by coremltools.

**Comment by aseemw** [comment]
Yes, YOLO model does not have cycles, so that should work.

**Comment by mbenami** [comment]
what about Faster-rcnn?

**Comment by younatics** [comment]
When we can use `tf.nn.bidirectional_dynamic_rnn`?

**Comment by BIOTONIC** [comment]
@aseemw Any plan to support BLSTM?

**Comment by iamasimkhan** [comment]
@aseemw Could you please tell me about a frozen_inference_graph.pb created with the help of Tensorflow. 
I haven't converted it to be used for Mobile Apps. But I directly tried it to be converted into .MlModel with TensorFlowtoCoreML. 
Gave me the same error.

**Comment by eaigner** [comment]
+1 for BiRNN support

**Comment by roksqq** [comment]
@aseemw 
> And then use them to build a CoreML model directly using the neural network builder [API](https://apple.github.io/coremltools/generated/coremltools.models.neural_network.html) provided by coremltools.

Your provided API link doesn't work (404)

**Comment by aseemw** [comment]
This is link: https://apple.github.io/coremltools/generated/coremltools.models.neural_network.builder.html

**Comment by mrgloom** [comment]
I wonder where ssd model contains cycles? it look like just feedforward network.

```
WARNING:root:TensorFlow version 1.12.0 detected. Last version known to be fully compatible is 1.5.0 .

Loading the TF graph...
2019-03-11 12:34:45.237621: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Graph Loaded.
Traceback (most recent call last):
  File "ssd_sandbox/convert_from_tensorflow_to_coreml.py", line 20, in <module>
    convert_from_tensorflow_to_coreml(is_post_training_quantize=False)
  File "ssd_sandbox/convert_from_tensorflow_to_coreml.py", line 10, in convert_from_tensorflow_to_coreml
    'detection_classes:0', 'num_detections:0'])
  File "/usr/local/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 586, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/usr/local/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 167, in _convert_pb_to_mlmodel
    OPS = _topological_sort_ops(OPS)
  File "/usr/local/lib/python3.6/site-packages/tfcoreml/_tf_graph_transform.py", line 194, in _topological_sort_ops
    _push_stack(stack, node, in_stack)
  File "/usr/local/lib/python3.6/site-packages/tfcoreml/_tf_graph_transform.py", line 38, in _push_stack
    raise ValueError('Graph has cycles.')
ValueError: Graph has cycles.
```

**Comment by Mstronach** [comment]
This issue is being closed due to inactivity preceeding the request for an update. Please feel free to re-open. Thanks!

**Comment by dhgokul** [comment]
Me too got same error as mentioned by @Mstronach 
We used  SSD mobilenet version and generate protobuf file and tried to convert ML model we get same issue - PFA
![image](https://user-images.githubusercontent.com/5689804/78887068-dec1d600-7a7c-11ea-9f69-40e81f55ac58.png)


Any updates on this issue ?
