### ISSUE TITLE
ClassLabel not working properly

### ISSUE THREAD

**Issue by dhananjaykumardubey** [tf-coreml/tf-coreml#127]
Hi @aseemw ,

I converted my .pb into mlmodel, 
`input_tensor_shapes = {'Const_6:0':[1,32,64,3]} # batch size is 1
coreml_model_file = 'DJ3.mlmodel'	
output_tensor_names = ['Softmax_2:0']
frozen_model_file = 'modified_deepLogo.pb'

class_labels = [
    'Adidas', 'Apple', 'BMW', 'Citroen', 'Cocacola', 'DHL', 'Fedex', 'Ferrari',
    'Ford', 'Google', 'HP', 'Heineken', 'Intel', 'McDonalds', 'Mini', 'Nbc',
    'Nike', 'Pepsi', 'Porsche', 'Puma', 'RedBull', 'Sprite', 'Starbucks',
    'Texaco', 'Unicef', 'Vodafone', 'Yahoo', 'Background'
]

coreml_model = tfcoreml.convert(
        tf_model_path=frozen_model_file,
        mlmodel_path=coreml_model_file,
        image_input_names = 'Const_6:0',
        red_bias = -1,
        green_bias = -1,
        blue_bias = -1,
        is_bgr = True,
        image_scale = 2.0/255.0,
        input_name_shape_dict=input_tensor_shapes,
        output_feature_names=output_tensor_names, 
        class_labels=class_labels,
        predicted_feature_name=none,
        predicted_probabilities_output=' ')` 
While this works properly and converts into mlmodel. But when I integrate that model , then the prediction is always the first element of class label.

i.e in this case the prediction always comes "Adidas".

Can you please help me what am I doing wrong here?

**Comment by aseemw** [comment]
Can you check whether the output of the mlmodel matches the TF output for the same output. You can look at the python notebooks on how to do that.
If TF and Coreml match then there is no issue. (Maybe the TF model itself always gives adidas). If not, then something went wrong during conversion.

**Comment by dhananjaykumardubey** [comment]
Yes, The TF model and mlmodel both of them is giving "adidas", as this is the first element of my classLabel file.

**Comment by aseemw** [comment]
Okay. Then the converter did its job!
I guess you need to look into getting a better model:)
