### ISSUE TITLE
value Mismatches between python pb model and mlmodel in objective c

### ISSUE THREAD

**Issue by shdtech** [tf-coreml/tf-coreml#129]
i have successfully converted models and used them in the last few weeks, this new model having mismatches in the output between python pb model and the mlmodel in objective c, this time inputs are normalised, it runs on the gpu. 
for example the first pixel output in python is: -0.0009627791, while in objective c:-0.000590801239, i have mismatches in all pixels, all inputs are float32. i cut down the model to simple concat and conv layer and still getting mismatches, i am attaching the narrowed model:
i'm attaching the PB file and the 2 inputs and the mlmodel:

[Archive.zip](https://github.com/tf-coreml/tf-coreml/files/1720408/Archive.zip)

to run the model in python after importing the pb:

chan1_in = np.fromfile('...random_in1chan.bin',dtype=np.float32)
chan1_in = chan1_in.reshape(640,480,1)
chan3_in = np.fromfile('...random_in3chan.bin',dtype=np.float32)
chan3_in = chan3_in.reshape(640,480,3)

res = session.run(session.graph_def.node[-1].name + ':0', {session.graph_def.node[0].name + ':0': [chan3], session.graph_def.node[1].name+ ':0' : [chan1]})

**Comment by aseemw** [comment]
I think first of all, you should be looking at relative errors, especially for output values that are high.

There is some loss of precision in the GPU path as it uses Float 16. If the values (product of input and weights) are very small, there can be underflow, which means smaller values are rounded to zero. 
In this model, all the outputs are really small (~less than 10^-3/4). 
Ideally the network should be scaled.
