### ISSUE TITLE
Issue with split op

### ISSUE THREAD

**Issue by GhostGengar** [tf-coreml/tf-coreml#136]
Hi there,

Thank you for a really exciting project. I am getting the following error when trying to convert my AlexNet model

`NotImplementedError: Unsupported Ops of type: Split`

Is there any way that you can add support for `split` op?
Thank you

**Comment by aseemw** [comment]
Hi, can you pull PR #137 and check whether it works for the AlexNet model you are trying to convert.

**Comment by GhostGengar** [comment]
Hi, thanks for your response. It looks like the problem still retains. Below is the full error message
`  File "/Users/lukedinh/Environments/python27/lib/python2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 483, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "/Users/lukedinh/Environments/python27/lib/python2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 149, in _convert_pb_to_mlmodel
    _check_unsupported_ops(OPS, output_feature_names)
  File "/Users/lukedinh/Environments/python27/lib/python2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 117, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported Ops of type: Split`

**Comment by aseemw** [comment]
You should not be getting that anymore. Make sure you have checked out the PR branch and have installed the local repo (using pip install -e .)

You should be able to run this test: 
`pytest tests/test_tf_converter.py::TFSimpleNetworkTest::test_split`
