### ISSUE TITLE
The output generated with tf.stack can not be convert correctly in coreml

### ISSUE THREAD

**Issue by shishaozheng** [tf-coreml/tf-coreml#138]
I trained a tensorflow model that the output Tensor Shape is [?, 20, 23] ， I stack  20 Tensors with shape [23] to this output tensor using tf.stack。After converting to coreml model, the output shape become [1,1,23,1,1]. Can anyone tell me how to get the correct output shape in coreml?

**Comment by aseemw** [comment]
tf.stack is currently not supported. 
Can you give a few more details on what the graph you are trying to convert? Maybe a code snippet of the ops involved.

**Comment by shishaozheng** [comment]
@aseemw Thanks and here is the code of the output layer
`       
with tf.variable_scope('hidden10'):
    dense = tf.layers.dense(flatten, units=4096, activation=tf.nn.relu)
    hidden10 = tf.layers.dropout(dense, rate=drop_rate)

with tf.variable_scope('output1'):
    dense = tf.layers.dense(hidden10, units=23)
    output1 = dense
   
with tf.variable_scope('output2'):
    dense = tf.layers.dense(hidden10, units=23)
    output1 = dense

...
...

with tf.variable_scope('output20'):
    dense = tf.layers.dense(hidden10, units=23)
    output1 = dense

output = tf.stack([output1, output2, ... , output20], axis=1, name='output')
`

**Comment by shishaozheng** [comment]
I have tried export 20 outputs instead of stacking them. but after exported to coreml, these 20 outputs is disorder,  It is difficult to organize them to correct order.

I also tried using tf.concat instead of tf.stack. but an error occurred when converting:
AssertionError: Concat axis case not handled

**Comment by aseemw** [comment]
There is a bug in the converter in the way it handles the "pack/stack" TF op. It just skips these op types. This op is not really supported by CoreML so the converter should error out with an informative message.  

For your use case, you could use the tf.concat instead. The case should be handled after PR #141 is merged. Kindly look at the PR and the unitest added in it. You can test your model on the PR's branch.

**Comment by aseemw** [comment]
"pack" op is not supported in Core ML.
After PR #176 correct error message is raised.
