### ISSUE TITLE
Properly handle Pack/stack ops

### ISSUE THREAD

**Issue by aseemw** [tf-coreml/tf-coreml#142]
Currently these are skipped. Which is fine for most models, in which pack/stack is used to convert a bunch of scalars (0-D vectors) into a 1-D vector, which anyways gets optimized away. But in general this can lead to erroneous conversions. 
See issue #138

**Comment by Mstronach** [comment]
This issue is being closed as it has been resolved as a part of Core ML 3. Thanks!
