### ISSUE TITLE
compiler error:  Failed to copy empty or invalid weights to kernel

### ISSUE THREAD

**Issue by Jon889** [tf-coreml/tf-coreml#144]
I'm trying to convert a retrained [model](https://github.com/tf-coreml/tf-coreml/files/1822292/frozen_inference_graph_fe.pb.zip) based on the SSD MobileNet to CoreML. However I get the followed error:

```
Neural Network compiler 180: 290 , name = FeatureExtractor/MobilenetV1/zeros_1:0, Traceback (most recent call last):
  File "convert.py", line 73, in <module>
    image_scale = 2.0/255.0)
  File "/Users/jonathan/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 483, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "/Users/jonathan/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 368, in _convert_pb_to_mlmodel
    return MLModel(spec)
  File "/Users/jonathan/miniconda3/lib/python3.6/site-packages/coremltools/models/model.py", line 153, in __init__
    self.__proxy__ = _get_proxy_from_spec(filename)
  File "/Users/jonathan/miniconda3/lib/python3.6/site-packages/coremltools/models/model.py", line 77, in _get_proxy_from_spec
    return _MLModelProxy(filename)
RuntimeError: Error compiling model: "compiler error:  Failed to copy empty or invalid weights to kernel".
```

The complete output is [here](https://pastebin.com/BvcDJjSM)

This is after the CoreML model has been saved, however it doesn't seem to be valid in that the outputs are not matrices
<img width="336" alt="screen shot 2018-03-18 at 02 32 27" src="https://user-images.githubusercontent.com/389853/37561974-a1c2fce0-2a54-11e8-9b55-401f45084e15.png"> and also as you can see in the complete output of the conversion tool, there is no shape for the outputs.

As far as I can see the zeros_1 is just generating a matrix of 0s so I'm not sure how it can fail with copying empty or invalid weights. (The input pb file has been frozen btw)

I've used the code here: https://github.com/tf-coreml/tf-coreml/blob/master/examples/ssd_example.ipynb to do the conversion (very slightly modified to make the input an image type and to scale and add bias to it, https://github.com/tf-coreml/tf-coreml/issues/110#issuecomment-358888865, but even without these modifications it fails on my retrained model, but works on the original)

Some help figuring out this error would be greatly appreciated, thanks!

**Comment by PIRANAVARUBAN** [comment]
What did you did to solve the Issue ?
