### ISSUE TITLE
tensorflow pb to coreml error

### ISSUE THREAD

**Issue by SlZeroth** [tf-coreml/tf-coreml#145]
COMMAND : tf_converter.convert(tf_model_path = 'model.pb', mlmodel_path = 'ten.mlmodel', output_feature_names = ['softmax:0'], input_name_shape_dict = {'input:0': [1,256,256,3]})

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tfcoreml/_tf_coreml_converter.py", line 483, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "tfcoreml/_tf_coreml_converter.py", line 180, in _convert_pb_to_mlmodel
    "%s is a placeholder with incomplete shape %s" %(input_name, str(shape)))
AssertionError: Placeholder_1:0 is a placeholder with incomplete shape <unknown>

I got this error , what is the problem ?? 

and model.pb is image segmentation model .

**Comment by gi097** [comment]
You are probably using a wrong input name. What's the model you try to convert?

**Comment by DtechLabs** [comment]
I have the same error. Did you found solution?

**Comment by aseemw** [comment]
Can you try again by pulling the latest master? A few fixed were pushed in PR #161

**Comment by DtechLabs** [comment]
Thanks.  Converted without errors. Great
