### ISSUE TITLE
NotImplementedError: Unsupported Ops of type: Unpack,Select

### ISSUE THREAD

**Issue by amanmeetgarg** [tf-coreml/tf-coreml#146]
I am trying to convert the squeezeDet model as per the repository [Here](https://github.com/BichenWuUCB/squeezeDet).

While converting a file from the .pb to .mlmodel I am getting the errors as below.

The command is as follow:

`tf_converter.convert(tf_model_path = tf_model,
                     mlmodel_path = out_mlmodel,
                     output_feature_names = ['bbox/trimming/bbox','probability/score','probability/class_idx'],
                     input_name_shape_dict = {'batch' : [1, 640, 480, 3]})`

```
Traceback (most recent call last):
  File "converter.py", line 11, in <module>
    output_feature_names = ['bbox/trimming/bbox','probability/score','probability/class_idx'])
  File "/home/ubuntu/target_TFInstall/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 483, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "/home/ubuntu/target_TFInstall/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 149, in _convert_pb_to_mlmodel
    _check_unsupported_ops(OPS, output_feature_names)
  File "/home/ubuntu/target_TFInstall/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 117, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported Ops of type: `Unpack,Select`
```

both with the output as above and the input as below, I get the error of unsupported op type.

Is there something in the model operations that is not setup correctly ?

```
Traceback (most recent call last):
  File "converter.py", line 12, in <module>
    input_name_shape_dict = {'batch' : [1, 640, 480, 3]})
  File "/home/ubuntu/target_TFInstall/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 483, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "/home/ubuntu/target_TFInstall/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 149, in _convert_pb_to_mlmodel
    _check_unsupported_ops(OPS, output_feature_names)
  File "/home/ubuntu/target_TFInstall/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 117, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported Ops of type: Unpack,Select
```

**Comment by aseemw** [comment]
Yes, unfortunately these ops are currently not supported by CoreML. 
I think these ops are being used in the pre or post processing steps, so you should be able to remove them from the graph (e.g.: [ssd_example](https://github.com/tf-coreml/tf-coreml/blob/master/examples/ssd_example.ipynb) and convert rest of the network. 
Maybe discussion here could also be helpful: issue #107

**Comment by aseemw** [comment]
You can use custom layers for unsupported ops: PR #179

**Comment by 1duo** [comment]
This issue should be resolved with the latest coremltools. Close due to inactivity. Feel free to re-open if you still see the issue. Thanks!

**Comment by ahmedAlmasri** [comment]
any update about this issue

**Comment by aseemw** [comment]
These ops are supported, please use the minimum_deployment_target as '13' as indicated here : https://github.com/apple/coremltools/blob/master/examples/NeuralNetworkGuide.md#tensorflow-conversion

**Comment by ahmedAlmasri** [comment]
@aseemw I'm use minimum_ios_deployment_target as '13'  but get error 
ValueError: Shape of required input ImageTensor is not provided. I think this error related to ops

my script 

```
tf_converter.convert(tf_model_path = tf_model_path,
mlmodel_path = 'myfrozen_model.mlmodel',
output_feature_names = ['SemanticPredictions0'],
input_name_shape_dict = {'ImageTensor0' : [1, 227, 227, 3]},
minimum_ios_deployment_target='13',)
```
