### ISSUE TITLE
Error reading protobuf spec

### ISSUE THREAD

**Issue by PIRANAVARUBAN** [tf-coreml/tf-coreml#149]
Core ML model generated. Saved at location: model_name.mlmodel

Core ML input(s):
[name: "img_placeholder__0"
type {
imageType {
width: 300
height: 400
colorSpace: RGB
}
}
]
Core ML output(s):
[name: "preds__0"
type {
multiArrayType {
shape: 3
shape: 400
shape: 300
dataType: DOUBLE
}
}
]
Traceback (most recent call last):
File "/Users/4axis_admin/PycharmProjects/coverter/convert.py", line 6, in
image_input_names = ['img_placeholder__0'])
File "/Users/4axis_admin/PycharmProjects/coverter/tfcoreml/_tf_coreml_converter.py", line 483, in convert
predicted_probabilities_output=predicted_probabilities_output)
File "/Users/4axis_admin/PycharmProjects/coverter/tfcoreml/_tf_coreml_converter.py", line 368, in _convert_pb_to_mlmodel
return MLModel(spec)
File "/Users/4axis_admin/anaconda3/envs/neuralTest/lib/python2.7/site-packages/coremltools/models/model.py", line 153, in init
self.proxy = _get_proxy_from_spec(filename)
File "/Users/4axis_admin/anaconda3/envs/neuralTest/lib/python2.7/site-packages/coremltools/models/model.py", line 77, in _get_proxy_from_spec
return _MLModelProxy(filename)
RuntimeError: Error compiling model: "Error reading protobuf spec. validator error: Layer 'moments_15/normalize/divisor:0' consumes a layer named 'moments_15/sufficient_statistics/Const:0' which is not present in this network.".
[pbfile.zip](https://github.com/tf-coreml/tf-coreml/files/1844545/pbfile.zip)
[pbfile.zip](https://github.com/tf-coreml/tf-coreml/files/1844546/pbfile.zip)

**Comment by aseemw** [comment]
I have pushed fixes to PR #148, after which this network should work. 
Does this network use Instance batch normalization? There is an open issue (#26) in converting such networks through tfcoreml and evaluating on GPU, due to overflow. 
I think this network might have the same issue, however it should work accurately if you set the useCPUOnly flag to True.

**Comment by PIRANAVARUBAN** [comment]
Core ML model generated. Saved at location: test1.mlmodel 

Core ML input(s): 
 [name: "img_placeholder__0"
type {
  multiArrayType {
    shape: 3
    shape: 400
    shape: 300
    dataType: DOUBLE
  }
}
]
Core ML output(s): 
 [name: "preds__0"
type {
  multiArrayType {
    shape: 3
    shape: 400
    shape: 300
    dataType: DOUBLE
  }
}
]


Thanks aseemw it converts to mlmodel but
Earlier input is a Image type now it is a multiarray type any way t convert it to image type both input and output....

while having issue input is imagetype now it has changed to mutiarraytype

**Comment by aseemw** [comment]
I updated the style_transfer_example.ipynb example in PR #152. Please take a look.
Does that answer your question?

**Comment by PIRANAVARUBAN** [comment]
Yes It works.... thanks aeemw
