### ISSUE TITLE
Error: The model does not have a valid input feature of type image

### ISSUE THREAD

**Issue by jay58** [tf-coreml/tf-coreml#150]
Successfully Converted pb file to mlmodel.
![screen shot 2018-03-26 at 4 23 39 pm](https://user-images.githubusercontent.com/18693532/37902461-1ceb6df8-3112-11e8-9928-26277a31e9e1.png)

When using this model in the app then it says invalid input feature.

Then I compared it with ResNet50.mlmodel  and found that the input in Model Evaluation Parameters is different.

Resnet had following: 
![screen shot 2018-03-26 at 4 26 47 pm](https://user-images.githubusercontent.com/18693532/37902612-93d48e04-3112-11e8-9e0a-b764c4bfa3b1.png)

My Model had following:
![screen shot 2018-03-26 at 4 26 56 pm](https://user-images.githubusercontent.com/18693532/37902623-9cf4deb2-3112-11e8-94d9-69d859b3c355.png)

**Comment by aseemw** [comment]
I guess you are not passing the "image_input_names" argument while converting. 
(you can take a look at the jupyter notebooks in the example folder)

**Comment by jay58** [comment]
This is the conversion method that I am 

coreml_model = tfcoreml.convert(
    tf_model_path=tf_model,
    mlmodel_path=coreml_model,
    input_name_shape_dict=input_shapes,
    output_feature_names=output_layer,
    image_input_names = ['image'],
    class_labels = tf_labels,
    red_bias = -1,
    green_bias = -1,
    blue_bias = -1,
    image_scale = 2.0/255.0)

**Comment by jay58** [comment]
Changed Following code: 


coreml_model = tfcoreml.convert(
tf_model_path=tf_model,
mlmodel_path=coreml_model,
input_name_shape_dict=input_shapes,
output_feature_names=output_layer,
image_input_names = ['Mul:0'],
class_labels = tf_labels,
red_bias = -1,
green_bias = -1,
blue_bias = -1,
image_scale = 2.0/255.0)

**Comment by Gurdev-Singh** [comment]
I am also facing the same problem. I have even added the parameter of `image_input_names` but still my CoreML Model is showing input as MultiArray (3,299,299). Please help.
