### ISSUE TITLE
NotImplementedError: Unsupported Ops of type: FIFOQueueV2,QueueDequeueV2

### ISSUE THREAD

**Issue by Eddy-zheng** [tf-coreml/tf-coreml#153]
I use the official latest model training interface of tesorflow. The multi parallel readers that read data from the dataset. 

node {
  name: "parallel_read/common_queue_Dequeue"
  op: "QueueDequeueV2"
  input: "parallel_read/common_queue"
  device: "/device:CPU:0"
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          unknown_rank: true
        }
        shape {
          unknown_rank: true
        }
      }
    }
  }
  attr {
    key: "component_types"
    value {
      list {
        type: DT_STRING
        type: DT_STRING
      }
    }
  }
  attr {
    key: "timeout_ms"
    value {
      i: -1
    }
  }
}

op id 0 : op name: prefetch_queue/fifo_queue, op type: "FIFOQueueV2"
op id 1 : op name: fifo_queue_Dequeue, op type: "QueueDequeueV2"
op id 2 : op name: InceptionV1/Conv2d_1a_7x7/weights, op type: "Const"
op id 3 : op name: InceptionV1/Conv2d_1a_7x7/weights/read, op type: "Identity"
op id 4 : op name: InceptionV1/InceptionV1/Conv2d_1a_7x7/Conv2D, op type: "Conv2D"
op id 5 : op name: InceptionV1/InceptionV1/Conv2d_1a_7x7/BatchNorm/Const, op type: "Const"
op id 6 : op name: InceptionV1/Conv2d_1a_7x7/BatchNorm/beta, op type: "Const"
op id 7 : op name: InceptionV1/Conv2d_1a_7x7/BatchNorm/beta/read, op type: "Identity"
op id 8 : op name: InceptionV1/InceptionV1/Conv2d_1a_7x7/BatchNorm/Const_1, op type: "Const"
op id 9 : op name: InceptionV1/InceptionV1/Conv2d_1a_7x7/BatchNorm/Const_2, op type: "Const"
op id 10 : op name: InceptionV1/InceptionV1/Conv2d_1a_7x7/BatchNorm/FusedBatchNorm, op type: "FusedBatchNorm"

When can we support it？

**Comment by aseemw** [comment]
You should strip the graph of Queue-related ops, which are not supported as they are used for feeding training data, which does not make sense for CoreML as its an inference library.

**Comment by Eddy-zheng** [comment]
OK. Thanks, it has been solved.

**Comment by Dineshvijay** [comment]
@Eddy-zheng pls share the steps for removing ops
