### ISSUE TITLE
  Could not find a version that satisfies the requirement tfcoreml (from versions: )

### ISSUE THREAD

**Issue by WhereIsNaN** [tf-coreml/tf-coreml#157]
User-:~ user$ pip install -U tfcoreml
Collecting tfcoreml
  Could not find a version that satisfies the requirement tfcoreml (from versions: )
No matching distribution found for tfcoreml

**Comment by aseemw** [comment]
Can you specify more details about your system config? 
Pypi currently only has python 2 package. 
Does `pip install -e .` work when you run it from the root of the cloned repo?

**Comment by kramer425** [comment]
I had the same issue - this is what I had installed:

```
pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
numpy (1.14.2)
pip (9.0.3)
protobuf (3.5.2.post1)
setuptools (39.0.1)
six (1.11.0)
tensorflow-gpu (1.1.0)
Werkzeug (0.14.1)
wheel (0.31.0)
```

The `pip install -e .` command worked, however.

**Comment by aseemw** [comment]
Not sure about the reason. 
It could be because version of six is pinned to six==1.10.0, which is also pinned in [coremltools](https://github.com/apple/coremltools/issues/141) a dependency of tfcoreml.
