### ISSUE TITLE
AssertionError: ArgMax: Axis translation case not handled currently

### ISSUE THREAD

**Issue by younatics** [tf-coreml/tf-coreml#159]
Is there any plan to support argmax?

**Comment by aseemw** [comment]
Kindly specify more details about your use case.

**Comment by younatics** [comment]
Hello, @aseemw 
Actually I can't find Argmax in pb file too. 
So I think tf-coreml is not problem...! 
Do you know how to import Argmax in pb file too...?

```
with tf.name_scope('output'):
    W3 = tf.Variable(tf.random_uniform([second_hidden_layer_count, outputCount], -1., 1.))
    b3 = tf.Variable(tf.zeros([outputCount]))
    model = tf.add(tf.matmul(L2, W3), b3, name='Logits')
    softmax = tf.nn.softmax(model, name='Softmax')
    prediction = tf.argmax(model, 1, name='Prediction')
    output = tf.identity(prediction, name='Output')
```
I made my last scope like this, but I can't find argmax graph neither pb file nor coreml. :(

**Comment by asdemon** [comment]
you use the argmax in
```
prediction = tf.argmax(model, 1, name='Prediction')
```

**Comment by aseemw** [comment]
After PR #164 we should get a more informative error message. Can you try again after updating to the latest master.

**Comment by younatics** [comment]
Currently, I will close this issue and reopen again if same error occurred. 
Thanks!
