### ISSUE TITLE
how to add some ops when it does not support

### ISSUE THREAD

**Issue by asdemon** [tf-coreml/tf-coreml#163]
I want to turn a tf model to coreml,when I use this tool to convert, it issues:

```
NotImplementedError: Unsupported Ops of type: Range,GatherNd,FloorDiv,SparseTensorDenseAdd,Rank,AddN,ScatterNd
```

I want to know how I can add some ops to it when it does not support?

Thank you!

**Comment by aseemw** [comment]
Most of these ops are not supported by CoreML so they cannot be added to tfcoreml. 
To implement unsupported layers in CoreML, there is an option of using [custom layers](https://developer.apple.com/documentation/coreml/core_ml_api/creating_a_custom_layer).
However, tfcoreml does not currently provide a way to insert custom layers in the .mlmodel directly during conversion. An issue is open tracking that (#120). This will hopefully be added soon. 

Before trying to add unsupported TF ops as CoreML custom layers, it might be worthwhile to figure out where these ops are being used in your TF model. Maybe they can be removed by using the TF [graph transform tool](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md) and optimizing the TF graph. 

You can use [netron](https://github.com/lutzroeder/Netron) to visualize the frozen .pb file. Are these ops used in the pre-processing or post processing parts of the model? If yes, you can strip the graph of these ops and convert the remaining portion.

**Comment by asdemon** [comment]
aseemw, thank you for your reply, I have used the TF graph transform tool to optimize the model, and it is useful, but there are ops that can't remove, I'll see the custom layers to see how to solve this.

```
NotImplementedError: Unsupported Ops of type: GatherNd,FloorDiv,SparseTensorDenseAdd,AddN,ScatterNd
```

**Comment by aseemw** [comment]
can you attach the model or a Netron snapshot that shows how these unsupported ops are connected to the rest of the model architecture.

**Comment by asdemon** [comment]
@aseemw I use tf.sparse_add and tf.gather_nd to mimic tf.nn.max_pool_with_argmax on CPU, because tf.nn.max_pool_with_argmax is only implemented on GPU, and I use  tf.scatter_nd to implement an unpooling op, it takes max values and their index, output an unpool maxtrix

```
def unpool(net, mask, ksize=[1, 2, 2, 1], scope='unpool'):
# Thank you, @https://github.com/Pepslee
  with tf.name_scope(scope):
    input_shape = net.get_shape().as_list()
    #  calculation new shape
    output_shape = (input_shape[0], input_shape[1] * ksize[1], input_shape[2] * ksize[2], input_shape[3])
    # calculation indices for batch, height, width and feature maps
    one_like_mask = tf.ones_like(mask)
    batch_range = tf.reshape(tf.range(output_shape[0], dtype=tf.int64), shape=[input_shape[0], 1, 1, 1])
    b = one_like_mask * batch_range
    y = mask // (output_shape[2] * output_shape[3])
    x = mask % (output_shape[2] * output_shape[3]) // output_shape[3]
    feature_range = tf.range(output_shape[3], dtype=tf.int64)
    f = one_like_mask * feature_range
    # transpose indices & reshape update values to one dimension
    updates_size = tf.size(net)
    indices = tf.transpose(tf.reshape(tf.stack([b, y, x, f]), [4, updates_size]))
    values = tf.reshape(net, [updates_size])
    ret = tf.scatter_nd(indices, values, output_shape)
    return ret
```

**Comment by aseemw** [comment]
See PR #179
