### ISSUE TITLE
ImportError: No module named tfcoreml

### ISSUE THREAD

**Issue by MrThiago** [tf-coreml/tf-coreml#172]
I have installed all the required packages. 
Can you please advice ? thanks

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-77b5174f453f> in <module>()
----> 1 import tfcoreml
      2 mlmodel = tfcoreml.convert(
      3         tf_model_path = tf_model_path,
      4         mlmodel_path = './stylize.mlmodel',
      5         output_feature_names = ['Squeeze:0'],

ImportError: No module named tfcoreml

and

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-908bc0398199> in <module>()
     11 
     12 coreml_input = {'input__0': coreml_image_input, 'style_num__0': coreml_style_index}
---> 13 coreml_out = mlmodel.predict(coreml_input, useCPUOnly = True)['Squeeze__0']
     14 print coreml_out.shape, coreml_out.flatten()[:5]

NameError: name 'mlmodel' is not defined

**Comment by duplex143** [comment]
I'm also facing the same issue. Has it something to do with $PATH?
Btw, it should be `cd tf-coreml` instead of `cd tfcoreml`

**Comment by Saiktdey395** [comment]
Hi, I am facing a similar issue **ModuleNotFoundError: No module named 'tfcoreml'** when I run these commands in a python file or in Terminal- 

import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = '/myFilePath/frozen_inference_graph.pb',
                     mlmodel_path = '/myFilePath/frozen_inference_graph.mlmodel',
                     output_feature_names = ['softmax:0'])

what am I doing wrong?

**Comment by aseemw** [comment]
It seems that the tfcoreml package was not properly installed. 
Are all the dependencies listed in the readme.md file installed on your system?

**Comment by Mstronach** [comment]
Please try these instructions: https://github.com/tf-coreml/tf-coreml/blob/master/README.md#new-fire-tfcoreml-converter-with-core-ml-3 Please feel free to re-open if you are still seeing the issue. Thanks!

**Comment by claytonnarcis** [comment]
Tested on today Catalina and faced with the same issue. This is a fresh install on a new MacBook Air. Using python 3.7.5.

[Used this method]( https://github.com/tf-coreml/tf-coreml/blob/master/README.md#new-fire-tfcoreml-converter-with-core-ml-3 ) but faced with the same issue.

`Traceback (most recent call last):
File "convert-coreml-tf.py", line 2, in <module>
import tfcoreml as tf_converter
ModuleNotFoundError: No module named 'tfcoreml'`

Here is a dump of the version of library I'm running. 
`tensorflow                             2.0.0`
`tfcoreml                               1.0`

Let me know if you need more information.
