### ISSUE TITLE
Add support for Ops of type: Switch,Merge,Tile

### ISSUE THREAD

**Issue by shijianjian** [tf-coreml/tf-coreml#173]
------- 
---Update:
Sorry for the mess, just realized control flow is currently not acheivable on coreml side.
Keep it open for now, I may help implement the tile operation

----- 
I am trying to convert PointNet model into .mlmodel. It seems like some operations are still not supported, can you double check on it?
```
NotImplementedError                       Traceback (most recent call last)
<ipython-input-9-fa4404a4e1da> in <module>()
     11         mlmodel_path=coreml_model_file,
     12         input_name_shape_dict=input_tensor_shapes,
---> 13         output_feature_names=output_tensor_names)

/tf-coreml/tfcoreml/_tf_coreml_converter.py in convert(tf_model_path, mlmodel_path, output_feature_names, input_name_shape_dict, image_input_names, is_bgr, red_bias, green_bias, blue_bias, gray_bias, image_scale, class_labels, predicted_feature_name, predicted_probabilities_output)
    495       class_labels=class_labels,
    496       predicted_feature_name=predicted_feature_name,
--> 497       predicted_probabilities_output=predicted_probabilities_output)

/git/tf-coreml/tfcoreml/_tf_coreml_converter.py in _convert_pb_to_mlmodel(tf_model_path, mlmodel_path, output_feature_names, input_name_shape_dict, image_input_names, is_bgr, red_bias, green_bias, blue_bias, gray_bias, image_scale, class_labels, predicted_feature_name, predicted_probabilities_output)
    160   # 4. Check for unsupported ops
    161   OPS, skip_ops = _topological_sort_ops(OPS, output_feature_names) # do (1),(2),(3) listed above
--> 162   _check_unsupported_ops(OPS, output_feature_names, skip_ops) # do (4) listed above
    163 
    164   SHAPE_DICT = {} #Tensor name --> shape ({str: list})

/git/tf-coreml/tfcoreml/_tf_coreml_converter.py in _check_unsupported_ops(ops, output_feature_names, skip_ops)
    122     else:
    123       raise NotImplementedError("Unsupported Ops of type: %s" % (
--> 124         ','.join(unsupported_op_types)))
    125 
    126 def _convert_pb_to_mlmodel(tf_model_path,

NotImplementedError: Unsupported Ops of type: Switch,Merge,Tile
```

The corresponding methods are
```python
tf.cond() -- Switch,  Merge
tf.tile() -- Tile
```
I failed to evaluate (tf.cond()) nodes, which throws an error that indicates I have **not given the required placeholder values that are clearly provided.** When I ran the same code from .ckpt file straight away, the error changed to that '**Operation is marked as not fetchable'**. 

Can anyone give some comments about how to tackle this? Is it safe to skip evaluating tf.cond() related nodes?

**Comment by shijianjian** [comment]
Not possible to implement tf.tile for now, coremltools does not support it.

**Comment by Oktai15** [comment]
@shijianjian what about tf.cond? is it possible?

**Comment by shijianjian** [comment]
@Oktai15 As far as I know, CoreML need to build a static model all at once, tensors will always flow one from another. You cannot evaluate a tensor at run time then choose which one is the next tensor to go.

**Comment by Oktai15** [comment]
@shijianjian but TF builds static graph too, but they can change flow...

**Comment by Oktai15** [comment]
Or you say that it’s a problem with coremltools. Okay, got it. Do you know where I can see new progress in coremltools?

**Comment by shijianjian** [comment]
@Oktai15 You may check it on it's Github, but do not expect too much on solving the tf.cond or tf.switch staff. You need to go back to alter your model if you are making a product or something. 

As far as I know, I recorded some limitations of coremltools [here](https://medium.com/@jianshi_94445/convert-a-tensorflow-model-to-coreml-model-using-tfcoreml-8ce157f1bc3b). A lot of re-engneering need to do if you are working on some projects. Good luck :)
