### ISSUE TITLE
Issue Converting TensorFlow retrained Model to Core ML Model

### ISSUE THREAD

**Issue by 082rakesh** [tf-coreml/tf-coreml#174]
I am running the following commands and getting this result. 

<img width="807" alt="error" src="https://user-images.githubusercontent.com/1956785/39754203-101a3e4e-52df-11e8-9a99-0e878a7810fe.png">

Background:
I have cloned tensorflow for poets-2 modal from the below link
https://github.com/googlecodelabs/tensorflow-for-poets-2 
and retrain with the below script 

python scripts/retrain.py --output_graph=tf_files/retrained_graph.pb --output_labels=tf_files/retrained_labels.txt --image_dir=tf_files/flower_photos.

**Comment by Higgins2718** [comment]
Looks like you might have the wrong value for output_feature_names. Retraining the model changes the name of the output layer. You can download a program called Neutron on your Mac/PC to inspect the .pb file. Look at the name of the output layer and update your conversion file accordingly.

**Comment by 082rakesh** [comment]
Thanks for your suggestion Higgins2718. I have tried Neutron and also tried utils/inspect_pb.py to inspect pb files. Here is my pb details.
[text_file.txt](https://github.com/tf-coreml/tf-coreml/files/1986588/text_file.txt)

**Comment by Higgins2718** [comment]
Sure! If you scroll down to the bottom of text_file.txt (layer 514), you can see name = final_result:0.

In your conversion script, replace "Softmax" with "final_result:0". If you didn't retrain the model, Softmax would be correct. However, retraining adds this final layer to the model.

For reference, here's my conversion file with RGB biases:
```
import tfcoreml as tf_converter
class_labels = 'retrained_labels.txt'


image_input_name = ['input:0']
input_tensor_shapes = {"input":[1,229,229,3]} # batch size is 1
tf_converter.convert(tf_model_path = 'retrained_graph.pb',
                     mlmodel_path = 'my_model.mlmodel',
                     input_name_shape_dict=input_tensor_shapes,
                     output_feature_names = ['final_result:0'], image_input_names = image_input_name, red_bias = -1,
                     green_bias = -1,
                     blue_bias = -1, image_scale = 2.0/255.0, class_labels = class_labels)`

```

If you try your model on a smartphone and your predictions are messed up, it is most likely because you did not specify the correct RGB biases. Check test_pretrained_models.py to find the correct values for your version of Tensorflow (and see whether image scaling is necessary)

**Comment by 082rakesh** [comment]
Thanks for your input @Higgins2718 but no luck. I tried the same but still getting the same error. My changed converter..

import tfcoreml as tf_converter

tf_converter.convert(
    tf_model_path = "tf_files/quatized_graph.pb",
    mlmodel_path = "InceptionV3.mlmodel",
    output_feature_names = ['final_result:0'],
    )

So far I did :
I retrained the graph using

python scripts/retrain.py --output_graph=tf_files/retrained_graph.pb --output_labels=tf_files/retrained_labels.txt --image_dir=tf_files/flower_photos
 and generated tf_files/retrained_graph.pb

Then  optimized the graph of retrained .pb with below command:
python -m tensorflow.python.tools.optimize_for_inference   --input=tf_files/retrained_graph.pb   --output=tf_files/optimized1_graph.pb   --input_names="Mul"   --output_names="final_result"

and genrated tf_files/optimized_graph.pb

Last I quantize_graph with

python -m scripts/quantize_graph \
  --input=tf_files/optimized_graph.pb \
  --output=tf_files/rounded_graph.pb \
  --output_node_names=final_result \
  --mode=weights_rounded

and finally I have tf_files/rounded_graph.pb.

I do not know what I am missing for conversion.

**Comment by Higgins2718** [comment]
Hmm. Could you show me the traceback from running converter.py?

**Comment by 082rakesh** [comment]
I am new in python. May I know how do I get the traceback from running converter. I tried
 import traceback
traceback.print_stack()

within converter.py.

**Comment by Higgins2718** [comment]
Sure. Open up terminal. CD into the directory with converter.py.

Then, type "python converter.py" into terminal and copy the output of the program. Finally, comment it here and we can find the root of the problem.

**Comment by 082rakesh** [comment]
python converter.py
dyld: warning, LC_RPATH $ORIGIN/../../_solib_darwin_x86_64/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so being ignored in restricted program because it is a relative path
2018-05-09 22:39:32.224087: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "converter.py", line 7, in <module>
    output_feature_names = ['final_result:0'],
  File "/Library/Python/2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 483, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "/Library/Python/2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 180, in _convert_pb_to_mlmodel
    "%s is a placeholder with incomplete shape %s" %(input_name, str(shape)))
AssertionError: Mul:0 is a placeholder with incomplete shape <unknown>

**Comment by Higgins2718** [comment]
Ah, I think I see what's going on. Would you mind showing me your updated converter.py?

**Comment by 082rakesh** [comment]
<img width="1323" alt="screen shot 2018-05-09 at 10 44 44 pm" src="https://user-images.githubusercontent.com/1956785/39828983-9b22f642-53da-11e8-8009-77f57a28de03.png">

**Comment by Higgins2718** [comment]
You have a typo in tf_model_path. It should be "quantized" instead of "quatized"

Try this:

```
// replace with the name of your labels.txt file
class_labels = 'retrained_labels.txt'


image_input_name = ['input:0']
input_tensor_shapes = {"input":[1,229,229,3]} # batch size is 1
tf_converter.convert(tf_model_path = 'tf_files/quantized_graph.pb',
                     mlmodel_path = 'Inceptionv3.mlmodel',
                     input_name_shape_dict=input_tensor_shapes,
                     output_feature_names = ['final_result:0'], image_input_names = image_input_name, class_labels = class_labels)`
```

I think your problem is not including the input_name_shape_dict, image_input_names, and class_labels

**Comment by 082rakesh** [comment]
As per your suggestion I have updated my converter but still the same. This time error starts from last variable, if I delete class label, then next one and so on..

updated converter:

import tfcoreml as tf_converter

class_labels = 'retrained_labels.txt'
image_input_name = ['input:0']
input_tensor_shapes = {"input":[1,229,229,3]} # batch size is 1

tf_converter.convert(
    tf_model_path = 'tf_files/quatized_graph.pb',
    mlmodel_path = 'Inceptionv3.mlmodel',
    input_name_shape_dict=input_tensor_shapes,
    output_feature_names = ['final_result:0'], 
    image_input_names = image_input_name, 
    class_labels = class_labels)

error:
python converter.py
dyld: warning, LC_RPATH $ORIGIN/../../_solib_darwin_x86_64/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so being ignored in restricted program because it is a relative path
2018-05-09 23:09:02.737208: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "converter.py", line 13, in <module>
    class_labels = class_labels)
  File "/Library/Python/2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 483, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "/Library/Python/2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 180, in _convert_pb_to_mlmodel
    "%s is a placeholder with incomplete shape %s" %(input_name, str(shape)))
AssertionError: Mul:0 is a placeholder with incomplete shape <unknown>

Thinking to look back the whole process. stuck with same since yesterday...

**Comment by 082rakesh** [comment]
Yeah, I have typo but that I did while creation of graph. So my file name is tf_files/quatized_graph.pb only.

**Comment by Higgins2718** [comment]
Hmm. You're right— it might be wise to start over on the conversion process.

Check out  test_pretrained_models.py. The file provides examples for tensorflor -> coreML conversions. It might be just what you need.

**Comment by aseemw** [comment]
In the "test_file.txt" that you attached, look for "op type = ( Placeholder )". This is the op that feeds in the input. You'd see that the output name for that op is "Mul:0". This should be your input. Hence,
`input_tensor_shapes = {"Mul:0":[1,229,229,3]} # batch size is 1`
You could also find the input name by visualizing the model using Netron and looking at the summary tab. 

Please go through the jupyter notebooks in the repo. They discuss in detail the process of finding the input and output names.

**Comment by 082rakesh** [comment]
Thanks @aseemw. I am able to generate. I changed input_tensor_shapes and image_input_name. @Higgins2718 Thanks for your quick turnaround.
