### ISSUE TITLE
Cannot feed value of shape (1, 1000, 1500, 3) 

### ISSUE THREAD

**Issue by aboodi46** [tf-coreml/tf-coreml#181]
Hi, 

when I try examples of inception_v1 the dog picture prediction gave me the this error

Cannot feed value of shape (1, 1000, 1500, 3) for Tensor 'input:0', which has shape '(1, 224, 224, 3)'

any Idea? 

thanks

**Comment by aseemw** [comment]
As the error message implies, it seems you are feeding in an image of incorrect shape.
