### ISSUE TITLE
Help converting retrained MobileNet model

### ISSUE THREAD

**Issue by evanb2** [tf-coreml/tf-coreml#191]
I've retrained a MobileNet model following the tensorflow-for-poets-2 tutorial, using images of food.

My model is using an image size of 224.

I've converted this model with the following code:
```python
tf_model_path = './models/chroma_v4/food_graph_mobilenet_05242018.pb'

image_labels = './models/chroma_v4/food_labels_mobilenet_05242018.txt'

input_tensor_shapes = {'input': [1, 229, 229, 3]}  # batch size is 1

# Convert frozen graph to mlmodel
coreml_model = tf_converter.convert(
    tf_model_path=tf_model_path,
    mlmodel_path='./models/chroma_v4/chroma_v4.mlmodel',
    input_name_shape_dict=input_tensor_shapes,
    output_feature_names=['final_result:0'],
    image_input_names=['input:0'],
    red_bias=-1,
    green_bias=-1,
    blue_bias=-1,
    class_labels=image_labels)
```
Here's the output:
```
Core ML model generated. Saved at location: ./models/chroma_v4/chroma_v4.mlmodel

Core ML input(s):
 [name: "input__0"
type {
  imageType {
    width: 224
    height: 224
    colorSpace: RGB
  }
}
]
Core ML output(s):
 [name: "final_result__0"
type {
  dictionaryType {
    stringKeyType {
    }
  }
}
, name: "classLabel"
type {
  stringType {
  }
}
]
```
To test the model inference I'm running this:
```python
coreml_model = MLModel(
    './models/chroma_v4/chroma_v4.mlmodel')

# This is an image of a bagel
img_url = 'https://kossars.com/wp-content/uploads/2015/12/bagel-plain.jpg'
response = requests.get(img_url)
img = Image.open(BytesIO(response.content))

img = img.resize([224, 224], Image.ANTIALIAS)
coreml_inputs = {'input__0': img}
coreml_output = coreml_model.predict(coreml_inputs, useCPUOnly=False)

print('Label =', coreml_output['classLabel'])
```
But I've tested several images and all I get is:
`$ Label = nothing`

I'm going back to retest the TF model, but I wanted to check if there are any glaring issues with this conversion code. Thanks!

**Comment by aseemw** [comment]
For debugging purposes, can you try using it without the "class_labels" argument first? 
Also maybe you want to set the scale parameter as well.
(see inception_v1_preprocessing_steps.ipynb)

**Comment by evanb2** [comment]
Ok looks like the issue was setting the `image_scale=2.0/255.0` arg.

Now I'm correctly getting: `Label = bagel`

Can you explain what `image_scale` is doing here? And where the values `2.0/255.0` are derived from? I want to understand this better for future reference.

Thank you so much for your help!

**Comment by aseemw** [comment]
Its value depends on the original script used for training the model. So you'll need to look there. 

CoreML preprocessing applied the operation `scale * x + bias`, 
so if input image pixel values are in the interval [0,255] and 
scale=2/255, bias =-1, pre-processed values will be in the interval [-1,1] (I guess that is what mobilenet model uses for training)
