### ISSUE TITLE
Unsupported Ops of type: MaxPoolWithArgmax,ScatterNd

### ISSUE THREAD

**Issue by JeremyGozlan** [tf-coreml/tf-coreml#192]
Hey ! I can see those ops are still not in the list, will they be at any point? 
If not, if there anything i can do?
Thanks a lot for all the work!!!

**Comment by aseemw** [comment]
You can use custom layers, see PR#179

**Comment by 1duo** [comment]
Hi @JeremyGozlan, thanks for reporting this issue! `ScatterNd` op is now included in the latest coremltools. Let us know if you encounter any issues. `MaxPoolWithArgmax ` op in TF only has GPU implementation, and can be decomposed easily, let us know if you encounter an use case, we'd happy to look into it. Thanks!
