### ISSUE TITLE
Convert pb with two input and shows error

### ISSUE THREAD

**Issue by AlysonQ** [tf-coreml/tf-coreml#195]
Hi sirs,

Base on squeezenet , I  built a TensorFlow pb and did freeze_graph it. ([my pb file](https://drive.google.com/file/d/1z-I6aguLvIvsrQVzuKPvSlBARlUTGH1_/view?usp=sharing))
This pb has two input and one output.
**input:**
 name=batch_size, type=int32(3), shape=[1,160,160,3]
 name=phase_train, type=bool(10), shape=[1]
**output**
name=embeddings, op=Mul

Here is my convert code:

> import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = '/Users/qoo/facenet.pb',
                     mlmodel_path = '/Users/qoo/facenet.mlmodel',
                     output_feature_names = ['embeddings:0'],
                     input_name_shape_dict = {'batch_size:0':[1,160,160,3]},
                     image_input_names = ['batch_size:0'],
                     red_bias = -1,
                     green_bias = -1,
                     blue_bias = -1,
                     image_scale = 2.0/255.0)

And it shows error like this:

> Users/qoo/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-05-31 15:26:50.369532: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "convert.py", line 10, in <module>
    image_scale = 2.0/255.0)
  File "/Users/qoo/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 552, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/Users/qoo/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 198, in _convert_pb_to_mlmodel
    "%s is a placeholder with incomplete shape %s" %(input_name, str(shape)))
**AssertionError: phase_train:0 is a placeholder with incomplete shape <unknown>**

How should I do to convert this two input pb to cormel format?
Or maybe I should remove the unused input (phase_train)?

Thanks,
Alyson

**Comment by aseemw** [comment]
The error is raised because the second input's ("phase_train:0") shape has not been entered in `input_name_shape_dict`

It seems that the second input is training/dropout related, so it be great if you an remove it from the frozen graph. Issue #169 might be related

**Comment by AlysonQ** [comment]
Thanks for your quick reply!
but what if that I lost my checkpoint file of this model?

**Comment by aseemw** [comment]
You can still proceed with conversion. 
Your original script was incorrect since the graph has two inputs and the argument `input_name_shape_dict` contained shape of only the first input. 

You should try with 
`input_name_shape_dict = {'batch_size:0':[1,160,160,3], 'phase_train:0':[1]}`

 
I think, the second input is a dropout probability value. While executing the TF or coreml graph, the value of the second input should be 1 (i.e. there is no dropout during inference).

**Comment by ramiro-feria-puron** [comment]
@AlysonQ Did you figure out how to make it work? After including , 'phase_train:0':[1] this is what I get:

Shapes not found for 2738 tensors. Executing graph to determine shapes.
...
InvalidArgumentError: The second input must be a scalar, but it has shape [1]

**Comment by AlysonQ** [comment]
@ramiro-feria-puron I get the same error too. Still trying to solve it.

**Comment by aseemw** [comment]
Ignore my last comment, where I thought `phase_train:0` was a dropout related input. Its not. Its related to batchnorm while training. (I got that by visualizing the graph using this [script](https://github.com/tf-coreml/tf-coreml/blob/master/utils/visualize_pb.py))

Actually this TF graph is a training graph. What you need is an inference equivalent of this graph. I am not sure how to get that if you do not have access to the source code. 
But if you do have access to the code where the graph architecture was defined, then you could define an inference version of the graph and transfer the trained weights to it, and then freeze that to get the frozen .pb file. Please refer to the Tensorflow documentation. 


P.S.:
There are lots of training related ops in this graph (hence not supported on coreml). 
(e.g.: QueueDequeueUpToV2, FIFOQueueV2, StopGradient, Switch etc)  
(I got the op list by using this [script](https://github.com/tf-coreml/tf-coreml/blob/master/utils/inspect_pb.py))


OPS counts:
Sum : 1
AvgPool : 1
QueueDequeueUpToV2 : 1
BiasAdd : 1
Maximum : 1
FIFOQueueV2 : 1
MatMul : 1
Placeholder : 2
MaxPool : 3
ConcatV2 : 8
Relu : 25
StopGradient : 26
SquaredDifference : 26
Conv2D : 26
Rsqrt : 27
Square : 27
Squeeze : 53
Merge : 53
Add : 78
Mean : 78
Mul : 105
Sub : 182
Identity : 214
Switch : 236
Const : 272


Note that Squeezenet architecture is supported by CoreML. In fact there is an mlmodel [here](https://developer.apple.com/machine-learning/run-a-model/).

**Comment by CoderXWChu** [comment]
If it is a scalar, the input shape should be '[ ]',  
ref : [https://www.tensorflow.org/versions/r1.2/programmers_guide/dims_types](url)
you try this:
`input_name_shape_dict = {'batch_size:0':[1,160,160,3], 'phase_train:0':[]}`

**Comment by jfdream** [comment]
Hi，@AlysonQ Have you solved the problem ？（Convert facenet pb with two input and shows error）

**Comment by AlysonQ** [comment]
@jfdream  Nope :(
I found the other way to use this pd file.
But I still wonder how to convert,still debuging.

**Comment by DawerG** [comment]
Hello @AlysonQ,
You can try to feed your graph into the following utility function. It will strip off nodes not needed for the inference. 

tf.graph_util.remove_training_nodes()
Ref: https://www.tensorflow.org/api_docs/python/tf/graph_util/remove_training_nodes  

Also, could you please upload the .pb file again? The old link seems broken.

**Comment by mxmaxi007** [comment]
@AlysonQ I found a solution to solve this problem. You can try this setting:
input_name_shape_dict = {'batch_size:0':[1,160,160,3], 'phase_train:0':[1, 1, 1, 1]}.

It seems to accept array with  rank 3 or rank 5.
