### ISSUE TITLE
Converting custom slice operations

### ISSUE THREAD

**Issue by arjunkhare** [tf-coreml/tf-coreml#196]
I'm trying to convert a model which has multiple Slice operations with different operation names by following the example in the custom conversion example notebook and I'm running into some trouble.

During the conversion process, I get multiple outputs into the console saying that all the slice operations I am trying to convert get added as custom layers, but after printing the layers in the converted model, it looks like only the last slice operation gets converted and the rest are not part of the created mlmodel.

The code I have currently looks like:
```
def _convert_slice(**kwargs):
	tf_op = kwargs['op']
	coreml_nn_builder = kwargs['nn_builder']
	constant_inputs = kwargs['constant_inputs']

	params = NeuralNetwork_pb2.CustomLayerParams()
	params.className = 'Slice'
	params.description = 'Custom layer to convert tf op Slice'

	begin = constant_inputs.get(tf_op.inputs[1].name, [0, 0])
	size = constant_inputs.get(tf_op.inputs[2].name, [0, 0])

	begin_as_weights = params.weights.add()
	begin_as_weights.floatValue.extend(map(float, begin))
	size_as_weights = params.weights.add()
	size_as_weights.floatValue.extend(map(float, size))

	coreml_nn_builder.add_custom(name = tf_op.name,
						            input_names = [tf_op.inputs[0].name],
							    output_names = [tf_op.outputs[0].name],
							    custom_proto_spec = params)

coreml_model = tf_converter.convert(tf_model_path = tf_model_p,
                                    mlmodel_path = mlmodel_p,
                                    input_name_shape_dict = {'data:0':[1, 100, 100, 3]},
                                    output_feature_names = ['shared/prediction:0', 'shared/prediction2:0'],
                                    image_input_names = ['data:0'],
                                    add_custom_layers = True,
                                    custom_conversion_functions = {'shared/Slice_7':_convert_slice,
							                                       'shared/Slice_6':_convert_slice,
							                                       'shared/Slice_5':_convert_slice,
							                                       'shared/Slice_4':_convert_slice,
							                                       'shared/Slice_3':_convert_slice,
							                                       'shared/Slice_2':_convert_slice,
							                                       'shared/Slice_1':_convert_slice,
                                                                                                 'shared/Slice':_convert_slice})

```

However after conversion, I can only see that the last "shared/Slice" is in the mlmodel; none of the "shared/Slice_*" layers are there even though during the conversion process I get outputs such as:

Analysing op name: shared/Slice_7 ( type:  Slice )
Adding custom layer
Analysing op name: shared/Sum_7 ( type:  Sum )
Analysing op name: shared/Slice_6 ( type:  Slice )
Adding custom layer
Analysing op name: shared/Sum_6 ( type:  Sum )
...

Any help would be appreciated, I'm not sure as to why this problem is occuring.

**Comment by arjunkhare** [comment]
![image](https://user-images.githubusercontent.com/11065339/41063788-828b9458-698e-11e8-9792-a672d8c0488e.png)

Here is an image of the architecture in the relevant area

**Comment by aseemw** [comment]
I have not been able to reproduce the issue. 
I tried defining a toy TF with multiple slice ops and converted it with custom layers. I could see multiple custom layers. 

```
tf.reset_default_graph()
graph = tf.Graph()
with graph.as_default() as g:
    x = tf.placeholder(tf.float32, shape=[None,9], name="input")
    y = tf.layers.dense(inputs=x, units=12, activation=tf.nn.relu)
    z1 = tf.slice(y, [0,0], [1,3])
    z2 = tf.slice(y, [0,4], [1,3])
    z3 = tf.slice(y, [0,6], [1,3])
    y = tf.add(z1, z2)
    y = tf.add(y, z3, name='output')
```

```
coreml_model = tfcoreml.convert(
        tf_model_path=frozen_model_file,
        mlmodel_path=coreml_model_path,
        input_name_shape_dict={'input:0':[1,9]},
        output_feature_names=['output:0'],
        add_custom_layers=True,
        custom_conversion_functions={'Slice': _convert_slice,
                                     'Slice_1': _convert_slice,
                                     'Slice_2': _convert_slice})
```

Can you make a small example TF graph where you see the issue?

**Comment by arjunkhare** [comment]
Sorry about that aseem, it looks like when I converted another custom operation, I was not taking the inputs correctly which led to only one of the slice operations showing after printing the layers.
