### ISSUE TITLE
tf-coreml  and  coremltools 2.0b1 incompatible ? 

### ISSUE THREAD

**Issue by QuantumLeaves** [tf-coreml/tf-coreml#197]
Could not find a version that satisfies the requirement coremltools>=0.8 (from tfcoreml) (from versions: )
No matching distribution found for coremltools>=0.8 (from tfcoreml)

**Comment by aseemw** [comment]
I have not been able to reproduce this error. Can you outline the steps, or the order in which you installed the packages that led you to this error? 

Did you try installing coremltools 0.8 first, then installing tfcoreml, and then upgrading to coremltools to 2.0b1? 

Although for me, installing coremltools 2.0b1 and then tfcoreml 0.2.0 also worked.

**Comment by Mstronach** [comment]
This issue is being closed due to inactivity preceeding the request for an update. Please feel free to re-open if you are still seeing the issue. Thanks!
