### ISSUE TITLE
Error in _find_unused_ops for operations with output size 0

### ISSUE THREAD

**Issue by classner** [tf-coreml/tf-coreml#202]
Hi tfcoreml team,

I encountered a bug in _find_unused_ops in https://github.com/tf-coreml/tf-coreml/blob/master/tfcoreml/_tf_graph_transform.py#L107 . For operations with zero sized outputs (a corner-case, but relevant), this line fails. Suggested fix is to insert a check before:

```
if out1.size == 0 and out2.size == 0:
    is_skippable = True
    continue
```

**Comment by aseemw** [comment]
Thank you for pointing that out. Do you want to put up a PR with a fix? 
Otherwise I'll put up one soon. Thanks!

**Comment by classner** [comment]
No problem! It would be great if you can put up the PR.

Thanks a lot!

**Comment by Mstronach** [comment]
@aseemw did you put up a PR regarding this issue?

**Comment by aseemw** [comment]
I have created it now PR #350
