### ISSUE TITLE
Image scaling before inference in preprocess

### ISSUE THREAD

**Issue by tanndx17** [tf-coreml/tf-coreml#208]
Hi,can anyone tell me the image_scale=2./255 part in the model inference. I dont't see any image scaling preprocess step in tensorflow object detection api demo code. https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb
or the inference code. 
Is that prequisite or optional,..or it's already included somewhere? If I deploy this on mobile devices, must I do the image scaling step before feed into the sess.run()?

Thanks!

**Comment by aseemw** [comment]
you don't always need it. Sometime the preprocessing is built into the TF graph itself.
