### ISSUE TITLE
Add custom layer that is not included in TF

### ISSUE THREAD

**Issue by minhohihi** [tf-coreml/tf-coreml#212]
I'm trying to implement custom layer that is not implemented in TF. I read tutorial (https://github.com/tf-coreml/tf-coreml/blob/master/examples/custom_layer_examples.ipynb) but sample examples (Tile, TopK, Slice) are all about unsupported layers in CoreML but implemented layer in TF. 

Is there any way implementing all new custom layer for CoreML like this description (http://machinethink.net/blog/coreml-custom-layers/)?

Thank you~

**Comment by aseemw** [comment]
You can directly use the NN [builder](https://apple.github.io/coremltools/generated/coremltools.models.neural_network.builder.html) to add layers (including custom layers) and build a CoreML model from scratch.

**Comment by bhushan23** [comment]
@minhohihi you can also use `custom_conversion_function` here https://github.com/apple/coremltools/blob/master/coremltools/converters/tensorflow/test/test_custom_layer.py 
closing this issue. Please feel free to re-open if you need more help
