### ISSUE TITLE
I can´t get MultiArray double as output

### ISSUE THREAD

**Issue by periscopiojoe** [tf-coreml/tf-coreml#221]
I am trying to train your model with my data. Input data is in the proper format and it is working.
I got it, but this what it happens when I try to implement in IOS:

Model analyzes the input. Returns a data. I expect that it will returns MultiArray(Double)
but it returns MultiArray(Double 4 x 1917 x 1)
Application receives unexpected data and crashes

How can I get "MultiArray double" instead " MultiArray(Double 4 x 1917 x 1)"?
Thanks and congrats for your georgeous work

Best regards

**Comment by periscopiojoe** [comment]
Here is the code I use to convert the model:
`# Now we have a TF model ready to be converted to CoreML
import tfcoreml
# Supply a dictionary of input tensors' name and shape (with # batch axis)
input_tensor_shapes = {"Preprocessor/sub:0":[1,300,300,3]} # batch size is 1
# Output CoreML model path
coreml_model_file = example_dir + 'ssd_mobilenet_feature_extractor.mlmodel'
# The TF model's ouput tensor name
output_tensor_names = ['concat:0', 'concat_1:0']

# Call the converter. This may take a while
coreml_model = tfcoreml.convert(
        tf_model_path=frozen_model_file,
        mlmodel_path=coreml_model_file,
        input_name_shape_dict=input_tensor_shapes,
        image_input_names = 'Preprocessor/sub:0',
        output_feature_names=output_tensor_names)

# CoreML saved at location: `/example_dir/tfcoreml_ssd_example/ssd_mobilenet_feature_extractor.mlmodel`

**Comment by periscopiojoe** [comment]
And this is the result I get. I would need a MultiArray DOuble for concat_0
![andrey3](https://user-images.githubusercontent.com/29833194/42936965-f21342c2-8b4d-11e8-8c0d-1b270b2d2716.png)

thanks

**Comment by aseemw** [comment]
what is the shape of the two output tensors in the TF graph? (you can find that by executing the graph and checking the shape of the returned result)

**Comment by AdamWP** [comment]
@periscopiojoe were you able to resolve this?  I am getting MultiArray (Double4 x 1917 x 1) for concat_1_0

**Comment by Mstronach** [comment]
This issue is being closed due to inactivity preceeding the request for an update. Please feel free to re-open if you are still seeing the issue. Thanks!
