### ISSUE TITLE
Logic behind input shape change

### ISSUE THREAD

**Issue by ElteHupkes** [tf-coreml/tf-coreml#223]
I'm converting a MobileNet V2 style model, which has an input tensor of 256x256x3 (height, width, channels). After conversion the tensor comes out as 3x256x256, which experimentally turns out to be (channels, height, width). It is of little consequence to me as I have to preprocess the data anyway, but I am curious about the logic behind this shape change, and why just the channels have gotten to the front without the height / width order changing. Does this have something to do with CoreML internals?

**Comment by DawerG** [comment]
Yes, that's just a chosen internal representation of images/feature maps in coremltools.

**Comment by ElteHupkes** [comment]
Okay, thanks for the info, I was just a bit puzzled. The model's working perfectly (and significantly faster than with tflite on Android...) so thanks for all the good work!
