### ISSUE TITLE
Wrong shape after conversion

### ISSUE THREAD

**Issue by kirualex** [tf-coreml/tf-coreml#229]
My original .pb model has an input with a shape of [12], but it's converted to [1,1,1] in my .mlmodel. 
The original shape is supposed to be a sequence of 12 doubles to distribute weights on a style transfer model.
I don't know how to use the second shape for the same purpose.

**Comment by aseemw** [comment]
Can you post the model or the [summary](https://github.com/tf-coreml/tf-coreml/blob/master/utils/inspect_pb.py) of the model? Thanks.

**Comment by kirualex** [comment]
[summary.txt](https://github.com/tf-coreml/tf-coreml/files/2263046/summary.txt)

**Comment by DawerG** [comment]
@kirualex Thanks for posting the summary. 

Just for an experiment, can you please set the option **self.use_dfs_shape_infer = False** and run the converter again? https://github.com/tf-coreml/tf-coreml/blob/c9d2052409b1af0232a610fc39ef4ec7ccc45d30/tfcoreml/_tf_coreml_converter.py#L40

**Comment by aseemw** [comment]
@kirualex If you look at the description of the [1,1,1] sized input generated by the converter it says "This input is a sequence of length 12"

Since for CoreML all tensors are rank-5 with the ordering [Seq, Batch, Channel, Height, Width], you should be able to run the Coreml graph with an input that has the shape [12,1,1,1,1].

**Comment by kirualex** [comment]
@aseemw It works! I can indeed load an MLMultiArray of shape [12,1,1,1,1] into the [1,1,1] input.
Maybe the .mlmodel input description should be a little more explicit on this? Like : 
`This input is a sequence of length N. Feed it an MLMultiArray of shape [N,1,1,1,1]`.

**Comment by aseemw** [comment]
Agreed. It should be more descriptive.

**Comment by Mstronach** [comment]
@aseemw can we close this issue, was the PR completed or should it remain open?

**Comment by aseemw** [comment]
We can close it now, since with the ios 13 deployment flag, the mlmodels generated do not have the discrepancy between shapes displayed in the mlmodel interface and at runtime.
