### ISSUE TITLE
Switching RGB to BGR during preprocessing? 

### ISSUE THREAD

**Issue by bigmit2011** [tf-coreml/tf-coreml#230]
Hi! My preprocessing of a custom model involved switching image channels from RGB to BGR.
However, it seems when trying to convert to a .ml model, I don't have any parameters that allows switching of channels?

''''tf_converter.convert(tf_model_path = model_path,
                     mlmodel_path = 'test2.mlmodel',
                     image_input_names = ['input_1:0'],
                     output_feature_names = ['output_node0:0'],
                     input_name_shape_dict = {'input_1:0' : [1, 299, 299, 3]},
                     image_scale= 2/255.0,
                     red_bias = -1,
                     green_bias = -1,
                     blue_bias = -1)'''

Sorry if I missed something  obvious.
Thank you very much

**Comment by aseemw** [comment]
There is a flag called "is_bgr" that maybe what you need
(https://github.com/tf-coreml/tf-coreml/blob/c9d2052409b1af0232a610fc39ef4ec7ccc45d30/tfcoreml/_tf_coreml_converter.py#L420)
