### ISSUE TITLE
After Convert Xcode Compile Error

### ISSUE THREAD

**Issue by fcu-d0515211** [tf-coreml/tf-coreml#231]
![image](https://user-images.githubusercontent.com/22321340/44306199-9132ba00-a3bc-11e8-9600-f66de9f88e15.png)

Swift 4.1
I build in Xcode 9.4.1

**Comment by Mstronach** [comment]
Hi, are you still experiencing this issue? Can you please provide an up to date screenshot or snippet of code that this issue is arising from? Please reopen if necessary. Thank you.
