### ISSUE TITLE
ValueError: output name: save/control_dependency, was provided, but the Tensorflow graph does not contain a tensor with this name.

### ISSUE THREAD

**Issue by gi097** [tf-coreml/tf-coreml#232]
I am trying to convert one of the following pertained models:

https://github.com/mrharicot/monodepth
http://visual.cs.ucl.ac.uk/pubs/monoDepth/models/model_cityscapes.zip

Using the following code:
```python
import tensorflow as tf
import tfcoreml as tf_converter
import operator
import sys

meta_path = 'model_cityscapes.meta'
output_node_names = ['save/control_dependency']

with tf.Session() as sess:

    # Restore the graph
    saver = tf.train.import_meta_graph(meta_path, clear_devices=True)

    graph = tf.get_default_graph()
    input_graph_def = graph.as_graph_def()
    sess = tf.Session()
    saver.restore(sess, "model_cityscapes")

    # Freeze the graph
    frozen_graph_def = tf.graph_util.convert_variables_to_constants(
        sess,
        sess.graph_def,
        output_node_names)

    # Save the frozen graph
    with open('output_graph.pb', 'wb') as f:
      f.write(frozen_graph_def.SerializeToString())


tf_converter.convert(tf_model_path = 'output_graph.pb',
                     mlmodel_path = 'output_graph.mlmodel',
                     output_feature_names = output_node_names)
```

I ran the summarize tool to get all the output node names. I am wondering why tf-coreml complains about the `save/control_dependency` since it must be included in the frozen graph. Is this a bug?

**Comment by aseemw** [comment]
The graph is not frozen properly. Instead of calling tf.graph_util.convert_variables_to_constants, please use the` from tensorflow.python.tools.freeze_graph import freeze_graph` as used in the example Jupiter-notebooks in this repo.

**Comment by gi097** [comment]
Thanks a lot! However that gives me the exact same error:

```python
import tensorflow as tf
import tfcoreml as tf_converter
import operator
import sys

from tensorflow.python.tools.freeze_graph import freeze_graph

meta_path = 'model_cityscapes.meta'
output_node_names = ['save/control_dependency']

with tf.Session() as sess:

    # Restore the graph
    saver = tf.train.import_meta_graph(meta_path, clear_devices=True)

    graph = tf.get_default_graph()
    input_graph_def = graph.as_graph_def()
    sess = tf.Session()
    saver.restore(sess, "model_cityscapes")

    init_op = tf.global_variables_initializer()
    sess.run(init_op)

    tf.train.write_graph(sess.graph_def, '.', 'output.pbtxt')  
    saver.save(sess, "./output.ckpt")

    graph_def_file = './output.pbtxt'
    checkpoint_file = './output.ckpt'
    frozen_model_file = './frozen_model.pb'
    output_node_name = 'save/control_dependency' 

    freeze_graph(input_graph=graph_def_file,
                input_saver="",
                input_binary=False,
                input_checkpoint=checkpoint_file,
                output_node_names=output_node_name,
                restore_op_name="save/restore_all",
                filename_tensor_name="save/Const:0",
                output_graph=frozen_model_file,
                clear_devices=True,
                initializer_nodes="")


tf_converter.convert(tf_model_path = frozen_model_file,
                     mlmodel_path = 'output_graph.mlmodel',
                     output_feature_names = output_node_names)
```

**Comment by aseemw** [comment]
Before calling the convert function, please make sure that the frozen graph is correct. 
You can use [Netron](https://github.com/lutzroeder/Netron) to visualize the graph. 

I think what is incorrect in the script above, that is causing a wrong frozen def is the name of the output
`output_node_name = 'save/control_dependency' `

It can be tricky to find the correct output of a TF graph. I looked at the .pbtxt file and picked the last Conv2D op, "model/decoder/Conv_17/convolution". Using that, the exported graph,  seems to be slightly better but it still doesn't have a 'placeholder' op for the input which it should have. However, that could be added "strip_unused_lib" function call (as used [here](https://github.com/tf-coreml/tf-coreml/blob/master/examples/inception_v3.ipynb)). 

To find the correct input and output op names, either you should look at the training source code that generated the graph in the first place. Or the summarize graph tool as described [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#inspecting-graphs) might also be useful.

**Comment by gi097** [comment]
The source is not really providing the output names. I also used the exact same summarize tool as you mentioned in the comment.

I might tweak around for a while but I will just think that this model is not suitable for CoreML yet.

Thanks for your help anyway!

**Comment by DawerG** [comment]
Another thing to note is that unlike freeze_graph, the `output_feature_names` argument of the function ` tf_converter ` accepts a list of tensor names (not the operation names). `output_node_names = ['save/control_dependency']` is a list of operation names. What should rather be provided to the converter is a list of tensor names `output_feature_names = ['save/control_dependency:0']`

**Comment by gi097** [comment]
Thanks :)
