### ISSUE TITLE
Can't convert mobilenet-ssd v2 

### ISSUE THREAD

**Issue by mpeniak** [tf-coreml/tf-coreml#235]
Hi guys,

I get these errors when converting:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-5e5f1fe6b115> in <module>()
      8 
      9 with tf.Graph().as_default() as g:
---> 10     tf.import_graph_def(original_gdef, name='')

/Users/mpeniak/Library/Python/2.7/lib/python/site-packages/tensorflow/python/util/deprecation.pyc in new_func(*args, **kwargs)
    430                 'in a future version' if date is None else ('after %s' % date),
    431                 instructions)
--> 432       return func(*args, **kwargs)
    433     return tf_decorator.make_decorator(func, new_func, 'deprecated',
    434                                        _add_deprecated_arg_notice_to_docstring(

/Users/mpeniak/Library/Python/2.7/lib/python/site-packages/tensorflow/python/framework/importer.pyc in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    568           raise ValueError('Duplicate name \'%s\' in GraphDef.' % node.name)
    569         if node.op not in op_dict:
--> 570           raise ValueError('No op named %s in defined operations.' % node.op)
    571         op_def = op_dict[node.op]
    572 

ValueError: No op named NonMaxSuppressionV3 in defined operations.

Whats the way to fix it please?

Thanks

**Comment by mabrowning** [comment]
tf-coreml is tuned to convert only the portion of the computational graph that does "core" convolutional layers. However, you can follow the steps in this article: https://machinethink.net/blog/mobilenet-ssdlite-coreml/ and possible the code in his repo https://github.com/hollance/coreml-survival-guide/tree/master/MobileNetV2%2BSSDLite to convert the whole graph into a mlmodel.

That said, iOS 12 does actually have a  Non Maximal Suppression `model` type: https://github.com/apple/coremltools/blob/master/mlmodel/format/NonMaximumSuppression.proto. tf-coreml might be able to "automate" some of hollance's technique.

**Comment by Mstronach** [comment]
Please try with the latest version and please feel free to reopen if you're still seeing this issue. Thanks!
