### ISSUE TITLE
How to output a picture

### ISSUE THREAD

**Issue by yihaozuifan** [tf-coreml/tf-coreml#237]
like  input,if I make image_input_names then I can  input a image.  now  I wan to a generate a image,but  I  can not found a type to make.  could you tell me  how can I do ?

**Comment by aseemw** [comment]
This notebook has example on setting output type as image: https://github.com/tf-coreml/tf-coreml/blob/master/examples/style_transfer_example.ipynb

**Comment by yihaozuifan** [comment]
tks very much  it's worked
