### ISSUE TITLE
Error declaring input for NN engine.

### ISSUE THREAD

**Issue by vladimiroster** [tf-coreml/tf-coreml#238]
Hi,
I've converted my TF model to CoreML using the package. The conversion went well, but when I try to load the model, I receive "Error declaring input for NN engine.". The python side is able to parse the model file correctly, but the native side is unable to load it.
Does anyone know what might be causing it?

Thanks!
Vlad

**Comment by aseemw** [comment]
Maybe the input size was incorrectly set? 
What is the input size in the .mlmodel and what sized MultiArray did you pass at runtime? 

If you can share the model (or an equivalent smaller version that displays the issue), it would be easy to debug.

**Comment by vladimiroster** [comment]
Thanks! The engine fails long before trying to run inference, the engine can't even load the converted model.
I've attached the model. The conversion is run using:
import tfcoreml as tf_converter
coreml_model = tf_converter.convert(tf_model_path = 'epsilon.tf',
                     mlmodel_path = 'output.mlmodel',
                     output_feature_names = ['action:0'],
                     input_name_shape_dict = {'vector_observation:0' : [1,8], 'epsilon:0' : [1,2]})

[epsilon.tf.zip](https://github.com/tf-coreml/tf-coreml/files/2390774/epsilon.tf.zip)

**Comment by aseemw** [comment]
I put up PR #239 that should fix this issue. Please try again using that branch. 

Btw, since in this model there are many other outputs which are not used, it is a good idea (although not required for this model) to simplify the TF model prior to conversion, using code similar to [here](https://github.com/tf-coreml/tf-coreml/blob/master/examples/ssd_example.ipynb). 
In particular, something like this: 

```
tf_model_path = 'models/Debug/model_issue_238.pb'
with open(tf_model_path, 'rb') as f:
    serialized = f.read()
tf.reset_default_graph()
original_gdef = tf.GraphDef()
original_gdef.ParseFromString(serialized)

with tf.Graph().as_default() as g:
    tf.import_graph_def(original_gdef, name='')

# Strip unused subgraphs and save it as another frozen TF model
from tensorflow.python.tools import strip_unused_lib
from tensorflow.python.framework import dtypes
from tensorflow.python.platform import gfile
input_node_names = ['vector_observation']
output_node_names = ['action']
gdef = strip_unused_lib.strip_unused(
    input_graph_def=original_gdef,
    input_node_names=input_node_names,
    output_node_names=output_node_names,
    placeholder_type_enum=dtypes.float32.as_datatype_enum)
# Save the feature extractor to an output file
frozen_model_file = 'models/Debug/model_issue_238_modified_graph.pb'
with gfile.GFile(frozen_model_file, "wb") as f:
    f.write(gdef.SerializeToString())
```

**Comment by vladimiroster** [comment]
Confirming the fix. Thanks a lot!
Yes, we usually cut down the unneeded branches.
