### ISSUE TITLE
failed to convert faster_rcnn_resnet101

### ISSUE THREAD

**Issue by woolfel** [tf-coreml/tf-coreml#250]
I just tried to convert faster_rcnn_resnet101_coco from google's model zoo and got an error.

File "/usr/local/lib/python2.7/site-packages/tfcoreml/_tf_graph_transform.py", line 38, in _push_stack raise ValueError('Graph has cycles.')

**Comment by aseemw** [comment]
Discussions in issue #189 and  #124 maybe relevant.

**Comment by Mstronach** [comment]
This issue is being closed due to inactivity preceeding the request for an update. Please feel free to re-open if you are still seeing the issue. Thanks!

**Comment by LinShihChieh** [comment]
Using the neural network builder API provided by coremltools. Is it the only way to convert rnn model or any graph has cycles? 

How to abstract the weight matrices and bias vectors from pre-trained model from tensorflow(.pb)
