### ISSUE TITLE
How can I make sure the input images are properly scaled and bias-added?

### ISSUE THREAD

**Issue by noeruh** [tf-coreml/tf-coreml#252]
I am using the following code to convert a mobilenet_v2 TF model to coreml model, the mobilenet_v2 model was downloaded from this page: https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet
```
import tfcoreml as tf_converter

tf_converter.convert(tf_model_path='mobilenet_v2_1.4_224_frozen.pb',
                     mlmodel_path='mobilenet_v2_1.4_224.mlmodel',
                     output_feature_names=['MobilenetV2/Predictions/Reshape_1:0'],
                     input_name_shape_dict={'input:0': [1, 224, 224, 3]},
                     image_input_names=['input:0'],
                     image_scale=2.0/255.0,
                     red_bias=-1,
                     green_bias=-1,
                     blue_bias=-1)
```

When I try to visualize the resulted mlmodel with Netron, I can't find a `scaler-layer`  which I expect will do scaling and bias adding stuffs:
<img width="320" alt="screen shot 2018-10-22 at 7 15 46 am" src="https://user-images.githubusercontent.com/36895558/47273633-633f4100-d5ca-11e8-90bf-90e16a05f67e.png">

However, visualizing another mlmodel example supplied by Apple: https://developer.apple.com/documentation/vision/classifying_images_with_vision_and_core_ml, I can find the `scaler-layer` inside the model:
<img width="349" alt="screen shot 2018-10-22 at 7 12 31 am" src="https://user-images.githubusercontent.com/36895558/47273612-e8762600-d5c9-11e8-9253-0cccaed9343d.png">

Am I doing it wrong? And what is the right way to make sure stuffs work as expected?

**Comment by aseemw** [comment]
Can you try printing the pre-processing info from the mlmodel (see [here](https://github.com/apple/coremltools/blob/e8b7655e0ef72a2a40075c6aad3453e253b94fb9/docs/APIExamples.md#printing-the-pre-processing-parameters)), to see whether the bias/scale params have been written to the model or not. If they are there, it could be an issue with Netron and not the converter.

**Comment by noeruh** [comment]
Thanks for the reply!

Printing the preprocessing params of the mlmodel outputs the following info:
```
[featureName: "input__0"
scaler {
  channelScale: 0.007843137718737125
  blueBias: -1.0
  greenBias: -1.0
  redBias: -1.0
}
]
```
I suppose it means that the scaler layer was successfully written into the mlmodel and I will close this issue.

**Comment by addisonklinke** [comment]
> Can you try printing the pre-processing info from the mlmodel (see here)

@aseemw FYI this link is broken because the master branch has evolved since your comment. Here is a [permalink](https://github.com/apple/coremltools/blob/e8b7655e0ef72a2a40075c6aad3453e253b94fb9/docs/APIExamples.md#printing-the-pre-processing-parameters) to the exact commit. If you could edit your comment, that might help future readers
