### ISSUE TITLE
Having issues with converting a custom tf model

### ISSUE THREAD

**Issue by s091704** [tf-coreml/tf-coreml#259]
Hi there,

I'm having problems with a conversion of a custom tf model. 
The model looks like this:
![image](https://user-images.githubusercontent.com/22317343/47638866-1cb88c00-db60-11e8-9631-61419f9ea2d6.png)

and after conversion(without errors) it looks like this:
![image](https://user-images.githubusercontent.com/22317343/47638901-35c13d00-db60-11e8-8502-fe5c2903335f.png)

Where is the add operator?

Another issue is that the output of the conversion gave me this:
Core ML input(s):
 [name: "x_placeholder__0"
type {
  multiArrayType {
    shape: 41
    dataType: DOUBLE
  }
}
]
Core ML output(s):
 [name: "softmax_prediction__0"
type {
  multiArrayType {
    shape: 2
    dataType: DOUBLE
  }
}
]

But my model has only float values? (conversion did actually change it from float32 to float64)
![image](https://user-images.githubusercontent.com/22317343/47639042-a1a3a580-db60-11e8-9245-a14deb1b7dd7.png)

![image](https://user-images.githubusercontent.com/22317343/47639008-8769c780-db60-11e8-996d-4ff83b30bc7b.png)

**Comment by aseemw** [comment]
- Add operator is fused with the "inner product" layer
- yes, by default the converter produces double types. You can change it back to float32 if you want using coremltools as shown [here](https://github.com/apple/coremltools/blob/master/docs/APIExamples.md#changing-mlmultiarray-inputoutput-datatypes)
