### ISSUE TITLE
Style transfer network predictions incorrect on GPU backend

### ISSUE THREAD

**Issue by slin07** [tf-coreml/tf-coreml#26]
This style transfer network can't be converted: 
[https://storage.googleapis.com/download.tensorflow.org/models/stylize_v1.zip]
In this style transfer network there're a bunch of quantization related ops that are not supported in CoreML. 
See `test_style_transfer ` in `tests/test_pretrained_models.py`.

**Comment by scsonic** [comment]
is the GPU issue fixed? or this is the problem of coreml @@ it's all nan on real iphone but works fine on iphone emultator.
