### ISSUE TITLE
Batchnorm applied to input layer fails to convert

### ISSUE THREAD

**Issue by lauriebyrum** [tf-coreml/tf-coreml#261]
Hi 
I have a graph that starts like:
batched_padded_input = tf.placeholder(tf.as_dtype(float32), shape=(1, 512, 512, 6), name='myinput')
net = tf.contrib.layers.batch_norm(
                batched_padded_input,
                decay=.9,
                scale=True,
                is_training=false,
                zero_debias_moving_mean=False,
                scope='bn', fused=True)

If I feed this graph into the converter, I get an error: 
  File "[...]/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 337, in _convert_pb_to_mlmodel
    convert_ops_to_layers(context)
  File "[...]/tf-coreml/tfcoreml/_ops_to_layers.py", line 180, in convert_ops_to_layers
    translator(op, context)
  File "[...]/tf-coreml/tfcoreml/_layers.py", line 79, in batchnorm
    num_channels = int(op.inputs[0].shape[-1])
TypeError: __int__ returned non-int (type NoneType)

In the debugger, it appears that inputs[0].shape hasn't been initialized in this case. If I remove this batchnorm, the model converts fine. I have other batchnorms later in the graph (they come after convolutions) that are fine.

**Comment by aseemw** [comment]
I added a test in PR #262 that seems to work just fine (with top of master of tfcoreml and tensor flow 1.11.0)

**Comment by lauriebyrum** [comment]
I will narrow this down further when i get a few cycles. Probably next week. Is a test pbtext useful or do you want a binary pb or tf code? Thanks for trying to repro.

**Comment by aseemw** [comment]
binary .pb is the best, because that is what the converter consumes

**Comment by lauriebyrum** [comment]
Hmm. I went back today, and I can't repro this anymore. One thing that changed is that I moved to using the transform_graph tool instead of optimize_for_inference_lib when I generated my pb files. Maybe that made the difference.  At any rate, we can close this and I'll report back if it somehow reappears. Sorry for the time waste!
