### ISSUE TITLE
Model conversion converts floating point inputs to doubles.

### ISSUE THREAD

**Issue by shashishekhar** [tf-coreml/tf-coreml#263]
It looks like when converting TF models the floating point inputs are converted to doubles.
https://github.com/apple/coremltools/blob/master/coremltools/models/datatypes.py#L119

When I converted mobilenets using tf-coreml(using https://github.com/tf-coreml/tf-coreml), the model input datatype was float but was converted to double.
https://github.com/tf-coreml/tf-coreml/blob/master/tfcoreml/_tf_coreml_converter.py#L298

I am not sure about the reason, but multiarray supports float32: https://developer.apple.com/documentation/coreml/mlmultiarraydatatype

**Comment by aseemw** [comment]
This is a converter bug. Currently the converter ignores the input data type and always uses the double datatype.

Its straightforward though, to get around it, see issue #242

**Comment by Mstronach** [comment]
Closing as workaround is available. Please let us know if the workaround works and reopen if there are any further issues. Thanks!
