### ISSUE TITLE
Converting Tensorflow model to CoreML model. Shape Translator missing for OP Slice

### ISSUE THREAD

**Issue by JakeWade5** [tf-coreml/tf-coreml#266]
Im using TFCoreml in python to convert my Tensorflow model into CoreML for development on an iOS device using the CoreML Libs.

Im using the following python code to try and convert the model to CoreML.

import tfcoreml as tf_converter

    tf_converter.convert(tf_model_path = 'frozen_inference_graph.pb', 
                         mlmodel_path = 'ml_model.mlmodel', 
                         output_feature_names = ['SemanticPredictions:0'],
                          input_name_shape_dict =  {'ImageTensor:0' : [1, 512, 512, 3]})

This gives the following error:

> Shape Translator missing for OP of type Slice.

I read the docs a bit further for TFCoreml and it states that Slice isn't fully supported, and some custom conversion code is required for this to work. In the TFCoreml documentation it suggests breaking the frozen graph into sub graphs and converting them individually then merging them back together post conversion.

I updated my code to use custom layers, but I don't really understand how the custom conversion functions work. 

Just need a few pointers on where to look to begin understanding how to write these custom conversion methods so I can solve my problem with converting the Tensorflow model to CoreML.

I did some more reading into the TFCoreml examples and documentation and have adapted my solution to this.

    import tfcoreml as tf_converter
    
    def _convert_slice(**kwargs):
        tf_op = kwargs["op"]
        coreml_nn_builder = kwargs["nn_builder"]
        constant_inputs = kwargs["constant_inputs"]
        
        params = NeuralNetwork_pb2.CustomLayerParams()
        params.className = 'Slice'
        params.description = "Custom layer that corresponds to the slice TF op"
        # get the value of begin
        begin = constant_inputs.get(tf_op.inputs[1].name, [0,0,0,0])
        size = constant_inputs.get(tf_op.inputs[2].name, [0,0,0,0])
        # add begin and size as two repeated weight fields
        begin_as_weights = params.weights.add()
        begin_as_weights.floatValue.extend(map(float, begin))
        size_as_weights = params.weights.add()
        size_as_weights.floatValue.extend(map(float, size))
        coreml_nn_builder.add_custom(name=tf_op.name,
                                    input_names=[tf_op.inputs[0].name],
                                    output_names=[tf_op.outputs[0].name],
                                    custom_proto_spec=params)
    
    coreml_model = tfcoreml.convert(
            tf_model_path='frozen_inference_graph.pb',
            mlmodel_path='my_model.mlmodel',
            input_name_shape_dict={'ImageTensor:0':[1, 512, 512, 3]},
            output_feature_names=['SemanticPredictions:0'],
            add_custom_layers=True,
            custom_conversion_functions={'Slice': _convert_slice}) # dictionary has op name as the key
    
    print("\n \n ML Model layers info: \n")
    # inspect the CoreML model: this should be same as the one we got above
    spec = coreml_model.get_spec()
    _print_coreml_nn_layer_info(spec)

I'm still getting the same error as before

> Shape Translator missing for OP of type Slice.

But i did notice I'm also getting this error/warning

> custom_conversion_functions={'Slice': _convert_slice}) # dictionary has op name as the key

Any assistance would be appreciated

**Comment by aseemw** [comment]
Can you try by replacing the line https://github.com/tf-coreml/tf-coreml/blob/master/tfcoreml/_interpret_shapes.py#L14 with
`return _terminate` ?

**Comment by meherkasam** [comment]
@aseemw I got the same error. I followed your recommendation. I stopped getting the error from the converter. However, the iPhone app would get stuck at the initialiser for the model file. Any ideas here?

**Comment by Mstronach** [comment]
@JakeWade5 Can you please try with latest build (coremltools 3.0+) and feel free to re-open if you are still seeing the issue. Thanks!
