### ISSUE TITLE
Unable to covert to semantic segmentation pb model to core ml 

### ISSUE THREAD

**Issue by anilsathyan7** [tf-coreml/tf-coreml#267]
We were trying to convert the deeplab semantic segmentation frozen graph(.pb) from the tensorflow deepl model zoo (
http://download.tensorflow.org/models/deeplabv3_mnv2_dm05_pascal_trainaug_2018_10_01.tar.gz)

But unfortunately we encountered the following error

```
>>> tf_converter.convert(tf_model_path = 'frozen_inference_graph.pb',
... mlmodel_path = 'myfrozen_model.mlmodel',
... output_feature_names = ['SemanticPredictions:0'],
... input_name_shape_dict = {'ImageTensor:0' : [1, 227, 227, 3]})

Loading the TF graph...
Graph Loaded.
Collecting all the 'Const' ops from the graph, by running it....
Done.
Now finding ops in the TF graph that can be dropped for inference
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Library/Python/2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 586, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/Library/Python/2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 286, in _convert_pb_to_mlmodel
    _check_unsupported_ops(OPS, output_feature_names, effectively_constant_ops + unused_ops)
  File "/Library/Python/2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 122, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported Ops of type: Shape,Pack
>>> 
```

It looks  like the operations in the official models are not supported by the tf-core ml tool ?
Or is there any way to specify them explicitly?
Any help would be highly appreciated
(Using Tensorflow 1.12.0,Python 2.7.10, Mac OS 10.14)

It looks similar to the following issues:-
https://stackoverflow.com/questions/53540822/converting-tensorflow-model-to-coreml-model-shape-translator-missing-for-op-sli
https://github.com/tf-coreml/tf-coreml/issues/146

Also how can we remove these layers related to post and preprocessing and set the input and shapes as fixed?

**Comment by anilsathyan7** [comment]
We got the latest version of the converter from the repo(clone), and changed couple of lines in 'tf-coreml/tfcoreml/_ops_to_layers.py' file. and  installed it from source.

Specifically, uncommented line 94 and 106 to include the corresponding ops
Now it works as expected !!!

**Comment by rajalive28** [comment]
@anilsathyan7 I am facing with the same issue. Could you please elaborate more on how did you fix it?

**Comment by SanthoshSandi** [comment]
Hello @1duo . I tried converting a modified deeplab model to coreml. I was unable to convert it..
Can you look into the conversion script once.

```
import tfcoreml as tf_converter

tf_converter.convert(tf_model_path='deeplab_dm1.0_inference.pb',
                     mlmodel_path='deeplab_2class.mlmodel',
                     output_feature_names=['ResizeBilinear_2:0'],
                     input_name_shape_dict={'sub_7:0': [1, 513, 513, 3]},
                     use_coreml_3=True)
```

This is the link for the sample model.

[Sample Model](https://github.com/ogl4jo3/LIYS_Application/raw/master/LIYS_DemoScript/Segmentation/models/deeplab_dm1.0_inference.pb)
