### ISSUE TITLE
iOS 12 can't read image from the converted model.

### ISSUE THREAD

**Issue by ZeroyiQ** [tf-coreml/tf-coreml#268]
hi!
I imitated your example.(style_transfer_example ) Successfully converted the model with the image output.
![2018-12-07 15-51-31](https://user-images.githubusercontent.com/16305800/49634540-07c0f980-fa38-11e8-9a35-24e47a1ed505.png)

However, I can't read image from the converted model on iOS 12. It returned me a CVPixelBufferRef type that is an invalid pointer address.(my english is bad, sor T_T)
![webwxgetmsgimg 1](https://user-images.githubusercontent.com/16305800/49633914-19a19d00-fa36-11e8-9f6b-069e6d2d1c23.jpeg)

**Comment by aseemw** [comment]
Not sure what's going on. 
- If you keep the output to be a multuarray type, then does it work correctly in Xcode? 
- in that case, for the multiarray output, do the values lie between 0 and 255? 
- when the output is of image type, does it work in python land with coremltools? in that case you should get back a PIL image.

**Comment by ZeroyiQ** [comment]
Could we use tf-coreml  or coreml to set the project  version to support iOS 12？

**Comment by Mstronach** [comment]
@ZeroyiQ Can you please try with latest build (coremltools 3.0+) and feel free to re-open if you are still seeing the issue. Thanks!
