### ISSUE TITLE
Converting mobile SSD fails

### ISSUE THREAD

**Issue by slin07** [tf-coreml/tf-coreml#27]
This mobile SSD model can't be converted:
[https://storage.googleapis.com/download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_android_export.zip]
In this mobile SSD there's a map operation and a while loop in preprocessing step, making it a loop. CoreML does not have support to realize map/while loop related ops. 
See `test_mobile_ssd` in `tests/test_pretrained_models.py` in branch `dev/ssd-test`.

**Comment by zampnrs** [comment]
@aseemw Do you have some updates on converting SSD models to CoreML? I'm having the same issue here with the **ssd_mobilenet_v2_quantized_coco** from the [tensorflow model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md). Should I consider change my neural net?
