### ISSUE TITLE
Tensorflow SavedModel format of mobilenet v2 to coreml

### ISSUE THREAD

**Issue by kshitizrimal** [tf-coreml/tf-coreml#274]
Hi,

I am having an issue converting my SavedModel format to coreml.

I have used tf.keras mobilenet v2 and added few dense layers and saved it as a SavedModel format of tensorflow.

I used following script for the convertion and got following error.

I believe my output layer name is dense_2, hence I wrote it there. Can anyone help me figuring this out?

<img width="1100" alt="screen shot 2019-01-07 at 4 51 42 pm" src="https://user-images.githubusercontent.com/628161/50771416-b617c300-12b2-11e9-9e81-7e6281d74034.png">
<img width="1020" alt="screen shot 2019-01-07 at 4 51 48 pm" src="https://user-images.githubusercontent.com/628161/50771428-bdd76780-12b2-11e9-94bf-df0d0e485de7.png">

**Comment by kshitizrimal** [comment]
@DawerG  What do you suggest, can be done to solve this issue?

**Comment by run-me** [comment]
Hey guys, did anyone solve this by any chance? kinda struck here, lol

**Comment by Mstronach** [comment]
Experimental support for TensorFlow 2.x and `tf.keras` was added in coremltools 3.1 with some [known issues](https://github.com/apple/coremltools/releases), could you please try again with the latest version of coremltools 3.1 and/or tfcoreml 1.1. Please see the [neural network conversion guide](https://github.com/apple/coremltools/blob/master/docs/NeuralNetworkGuide.md#tensorflow-converter) and/or [Jupyter notebooks](https://github.com/tf-coreml/tf-coreml/tree/master/examples) for some conversion examples. If you encounter any issues while converting your model, please [file a new GitHub issue](https://github.com/apple/coremltools/issues/new/choose) with steps to reproduce. Thanks!
