### ISSUE TITLE
Error : "The model does not have a valid input feature of type image"

### ISSUE THREAD

**Issue by vishnunairvp** [tf-coreml/tf-coreml#281]
I was trying to create a ios image recognition app with CoreML. I allready have the trained tensorflow lite model with me and tried to convert that into CoreML Model by following steps :-

git clone https://github.com/tf-coreml/tf-coreml.git

from the above github link have gone through the steps given in readme.md file to convert the retrained_graph.pb (trained tensorflow model that i got from https://www.tensorflow.org/lite/demo_ios ) to retrained_graph.mlmodel (core ml model).

In the TFCoreMLConverter.py file which got generated after installing the tf-coreml converter tool mentioned in readme file i gave the info as:

import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'retrained_graph.pb',
                     mlmodel_path = 'retrained_graph.mlmodel',
                     output_feature_names = ['final_result:0'])
 
It got converted to .mlmodel successfully but when i tried to run the model in ios the following error is occuring : 
Error : "The model does not have a valid input feature of type image" for the code : 
     try VNCoreMLModel(for: retrained_graph().model)

Help me with the issue. It is failing to load the model now.

**Comment by wandonye** [comment]
I have the same issue.
Looks like the input type is `MultiArray`

**Comment by aseemw** [comment]
converter command needs additional argument `image_input_names`, to mark an input as an image. Please take a look at some of the examples in https://github.com/tf-coreml/tf-coreml/tree/master/examples

**Comment by wandonye** [comment]
Yes, I was able to find the solution. The ssd example does not have `image_input_names` set. I will create a pull request when I have time, to make the ssd example runable.

**Comment by 1duo** [comment]
Looks like this issue has been resolved. Close due to inactivity, feel free to re-open or [file a bug](https://github.com/tf-coreml/tf-coreml/issues/new?assignees=&labels=bug&template=--bug-report.md&title=) if you still encounter any issues. Thanks!
