### ISSUE TITLE
unable to convert FALSR to CoreML

### ISSUE THREAD

**Issue by pashanhenlei** [tf-coreml/tf-coreml#282]
I got error like this:
File "/home/test/tf-coreml/tfcoreml/_shape_sensitive_layers.py", line 44, in _add_const
'Add constant: cannot add a constant in which all the dimensions ' \
AssertionError: Add constant: cannot add a constant in which all the dimensions (seq, C, H, W) are of non-unit size

and the code is:
tf_converter.convert(tf_model_path='pretrained_model/FALSR-B.pb', mlmodel_path='ml_model.mlmodel', output_feature_names=['test_sr_evaluator_i1_b0_g/target:0'], input_name_shape_dict = { 'input_image_evaluate_pbpr:0':[1,1024,512,2],'input_image_evaluate_y:0':[1,512,256,1]})

**Comment by 1duo** [comment]
This model should be able to convert with `coremltools==3.0.0` and `tfcoreml==1.0` or later. Please re-open if you still encounter issues. Thanks!
