### ISSUE TITLE
How identify the output parameters after use inspect_pb.py to use in convertor.py?

### ISSUE THREAD

**Issue by Jordi100** [tf-coreml/tf-coreml#285]
Hello,

Thank you for this tool. I appreciate.
My question is about how to identify the parameter that I need to use in convertor.py file?
For example:

output_feature_names = ['mul_16:0'],

These parameters appears at the end of the txt extension file after run the inspect_pb.py file.

OPS counts:
ExpandDims : 1
Tanh : 1
Placeholder : 1
Conv2DBackpropInput : 2
Relu : 10
Conv2D : 14
RealDiv : 16
Sub : 16
Pow : 16
SquaredDifference : 16
StopGradient : 16
Mul : 17
Mean : 32
Add : 38
Identity : 48
Dequantize : 82
Const : 281

The whole txt file is here:

http://www.fraudersity.com/summary1.txt

Regards,

Jorge

**Comment by aseemw** [comment]
I think its generally the last layer you need, `import/preds:0` in the txt file maybe

**Comment by Jordi100** [comment]
Hello Aseem,

Thank you for your answer.
I have seen the example of style transfer network here:

https://github.com/tf-coreml/tf-coreml/blob/master/examples/style_transfer_example.ipynb

Where I can see to convert to mlmodel (changing some parameters for my own pb extension  file):

import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'frozen1.pb',
                     mlmodel_path = 'Frozen1.mlmodel',
                     output_feature_names = ['preds:0'],
                     input_name_shape_dict = {'input:0':[1,256,256,3], 'style_num:0':[16]}
                     )

But it launch then error:

**Traceback (most recent call last):
  File "convertor.py", line 5, in <module>
    input_name_shape_dict = {'input:0':[1,256,256,3], 'style_num:0':[16]}
  File "/anaconda/lib/python2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 586, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/anaconda/lib/python2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 337, in _convert_pb_to_mlmodel
    convert_ops_to_layers(context)
  File "/anaconda/lib/python2.7/site-packages/tfcoreml/_ops_to_layers.py", line 178, in convert_ops_to_layers
    translator(op, context)
  File "/anaconda/lib/python2.7/site-packages/tfcoreml/_layers_common.py", line 77, in effectively_constant_op
    add_const(context, out.name, x, out.name)
  File "/anaconda/lib/python2.7/site-packages/tfcoreml/_layers_common.py", line 26, in add_const
    _add_const(context, name, x, output_name, shape)
  File "/anaconda/lib/python2.7/site-packages/tfcoreml/_shape_sensitive_layers.py", line 44, in _add_const
    'Add constant: cannot add a constant in which all the dimensions ' \
AssertionError: Add constant: cannot add a constant in which all the dimensions (Seq, C, H, W) are of non-unit size**

Please, how can it be solved?
REgards,

Jorge

**Comment by aseemw** [comment]
Hmm, it seems the graph needs to add a rank 4 tensor as a constant, however CoreML's load constant layer only supports max rank 3 tensor. 
One solution is to use custom layer. 
Can you check which constant tensor is this in the TF graph and what op it is feeding into?

**Comment by Jordi100** [comment]
Hello Aseem,

Sorry, I don t know how to check the constant tensor in the TF graph. Can you explain how?
I see the parameters in the summarize file I created, the parameters are:

OPS counts:
ExpandDims : 1
Tanh : 1
Placeholder : 1
Conv2DBackpropInput : 2
Relu : 10
Conv2D : 14
RealDiv : 16
Sub : 16
Pow : 16
SquaredDifference : 16
StopGradient : 16
Mul : 17
Mean : 32
Add : 38
Identity : 48
Dequantize : 82
Const : 281

REgards,

Jorge

**Comment by aseemw** [comment]
When you hit the error in `_layers_common.py` you can put a breakpoint and look up the name of the tensor, the arguments when the function `add_const(context, out.name, x, out.name)` is called

**Comment by Jordi100** [comment]
Hello Aseem,

I have added a Breakpoint just after the line:
_add_const(context, name, x, output_name, shape) in _layers_common.py
![img_2561](https://user-images.githubusercontent.com/21055773/53573957-e838f900-3b6e-11e9-8d62-ec93a6ab2337.JPG)

Now the error message is:
Traceback (most recent call last):
  File "convertor.py", line 5, in <module>
    input_name_shape_dict = {'input:0':[1,600,800,3], 'style_num:0':[16]}
  File "/anaconda/lib/python2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 586, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/anaconda/lib/python2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 337, in _convert_pb_to_mlmodel
    convert_ops_to_layers(context)
  File "/anaconda/lib/python2.7/site-packages/tfcoreml/_ops_to_layers.py", line 178, in convert_ops_to_layers
    translator(op, context)
  File "/anaconda/lib/python2.7/site-packages/tfcoreml/_layers_common.py", line 77, in effectively_constant_op
    add_const(context, out.name, x, out.name)
  File "/anaconda/lib/python2.7/site-packages/tfcoreml/_layers_common.py", line 26, in add_const
    _add_const(context, name, x, output_name, shape)
  File "/anaconda/lib/python2.7/site-packages/tfcoreml/_shape_sensitive_layers.py", line 44, in _add_const
    'Add constant: cannot add a constant in which all the dimensions ' \
AssertionError: Add constant: cannot add a constant in which all the dimensions (Seq, C, H, W) are of non-unit size

Can you tell me how to proceed?
Regards,
Jorge

**Comment by aseemw** [comment]
what is the value of variables `name` and `output_name` at the breakpoint?

**Comment by Jordi100** [comment]
Hi Aseem,

Sorry, I don t know how to check that. Please, how should I proceed?
Regards,
Jorge

**Comment by Jordi100** [comment]
Hello Aseem,

Does the following data helps?


Loading the TF graph...
Graph Loaded.
Collecting all the 'Const' ops from the graph, by running it....
Done.
Now finding ops in the TF graph that can be dropped for inference
Now starting translation to CoreML graph.
Automatic shape interpretation succeeded for input blob img_placeholder:0
1/607: Analysing op name: preds/y_max ( type:  Const )
2/607: Analysing op name: preds/y_min ( type:  Const )
3/607: Analysing op name: preds/y_quint8_const ( type:  Const )
4/607: Analysing op name: preds/y ( type:  Dequantize )
5/607: Analysing op name: mul_16/y_max ( type:  Const )
6/607: Analysing op name: mul_16/y_min ( type:  Const )
7/607: Analysing op name: mul_16/y_quint8_const ( type:  Const )
8/607: Analysing op name: mul_16/y ( type:  Dequantize )
9/607: Analysing op name: pow_15/y_max ( type:  Const )
10/607: Analysing op name: pow_15/y_min ( type:  Const )
11/607: Analysing op name: pow_15/y_quint8_const ( type:  Const )
12/607: Analysing op name: pow_15/y ( type:  Dequantize )
13/607: Analysing op name: add_35/y_max ( type:  Const )
14/607: Analysing op name: add_35/y_min ( type:  Const )
15/607: Analysing op name: add_35/y_quint8_const ( type:  Const )
16/607: Analysing op name: add_35/y ( type:  Dequantize )
17/607: Analysing op name: Variable_47_max ( type:  Const )
18/607: Analysing op name: Variable_47_min ( type:  Const )
19/607: Analysing op name: Variable_47_quint8_const ( type:  Const )
20/607: Analysing op name: Variable_47 ( type:  Dequantize )
21/607: Analysing op name: Variable_47/read ( type:  Identity )
22/607: Analysing op name: Variable_46_max ( type:  Const )
23/607: Analysing op name: Variable_46_min ( type:  Const )
24/607: Analysing op name: Variable_46_quint8_const ( type:  Const )
25/607: Analysing op name: Variable_46 ( type:  Dequantize )
26/607: Analysing op name: Variable_46/read ( type:  Identity )
27/607: Analysing op name: moments_15/variance/reduction_indices ( type:  Const )
28/607: Analysing op name: moments_15/mean/reduction_indices ( type:  Const )
29/607: Analysing op name: Variable_45_max ( type:  Const )
30/607: Analysing op name: Variable_45_min ( type:  Const )
31/607: Analysing op name: Variable_45_quint8_const ( type:  Const )
32/607: Analysing op name: Variable_45 ( type:  Dequantize )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "convertor.py", line 5, in <module>
    input_name_shape_dict = {'input:0':[1,600,800,3], 'style_num:0':[32]}
  File "tfcoreml/_tf_coreml_converter.py", line 586, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "tfcoreml/_tf_coreml_converter.py", line 337, in _convert_pb_to_mlmodel
    convert_ops_to_layers(context)
  File "tfcoreml/_ops_to_layers.py", line 180, in convert_ops_to_layers
    translator(op, context)
  File "tfcoreml/_layers_common.py", line 83, in effectively_constant_op
    x = context.session.run(out, feed_dict=context.input_feed_dict)
  File "tfcoreml/_layers_common.py", line 27, in add_const
    _add_const(context, name, x, output_name, shape)
  File "tfcoreml/_shape_sensitive_layers.py", line 44, in _add_const
    'Add constant: cannot add a constant in which all the dimensions ' \
AssertionError: Add constant: cannot add a constant in which all the dimensions (Seq, C, H, W) are of non-unit size

Regards,

Jorge

**Comment by aseemw** [comment]
Will need to look at the model (.pb) file, please file a bug at https://developer.apple.com/bug-reporting/ and attach the model to it. Thanks!

**Comment by Jordi100** [comment]
Dear Aseem,

Thank you. I will send now the .pb file to Apple.
Regards,

Jorge Martin

**Comment by Jordi100** [comment]
Dear Aseem,

I send the pb extension file more than a week ago to 
https://developer.apple.com/bug-reporting/ and nobody answered.
The ID for the question is 48804807, please can you take a look?
Regards,

Jorge

**Comment by aseemw** [comment]
Please try to convert the model again using PR #289

**Comment by aseemw** [comment]
Please do a fresh clone of the tf-coreml repo, or pull the latest master branch, 
then install the converter from source, by following the steps https://github.com/tf-coreml/tf-coreml#install-from-source

Then run the conversion script again.

**Comment by Jordi100** [comment]
Hello Aseem,

Thank you. After install again, it works. It converts to the ML model.
Now the issue is that in Xcode the mlmodel file must be an input image and an output image.
For example (please see image attached).
![IMG_2881](https://user-images.githubusercontent.com/21055773/55070022-a627a800-5085-11e9-9a10-7a63e3e256bb.JPG)

But in the model created the input is img_placeholder (Multiarray type)
And the output is a preds_0 (Multiarray type)
![IMG_2883](https://user-images.githubusercontent.com/21055773/55070208-06b6e500-5086-11e9-9c6e-87a0813f665e.JPG)

The parameters in convertor.py file I use are:
import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'frozen1.pb',
                     mlmodel_path = 'Frozen1.mlmodel',
                     output_feature_names = ['preds:0'],
                     input_name_shape_dict = {'input:0':[1,600,800,3], 'style_num:0':[32]}
                     )
Please, what must I change?
REgards,

Jorge

**Comment by Mstronach** [comment]
Please feel free to reopen this if you have further questions, Thanks!
