### ISSUE TITLE
Fused Batchnorm does not convert correctly

### ISSUE THREAD

**Issue by soon-yau** [tf-coreml/tf-coreml#288]
I have a frozen graph that is optimized where batchnorm layer is folded where the multiplication part is folded into convolution and the addition part is folded into the **bias add** which you can see in op type as shown below.
```
70: op name = import/Conv2d_0/batch_normalization/FusedBatchNorm, op type = ( BiasAdd 
), inputs = import/Conv2d_0/Conv2D:0, import/Conv2d_0/Conv2D_bn_offset:0, outputs = import/Conv2d_0/batch_normalization/FusedBatchNorm:0
@input shapes:
name = import/Conv2d_0/Conv2D:0 : (?, 112, 112, 24)
name = import/Conv2d_0/Conv2D_bn_offset:0 : (24,)
@output shapes:
name = import/Conv2d_0/batch_normalization/FusedBatchNorm:0 : (?, 112, 112, 24)

```
However, in the converted mlmodel, the layer type is still shown as **batchnorm**. I wonder if that has been converted wrongly which means it is still doing the full batchnorm which can slow down the inference considerably
```
1: layer name = Conv2d_0/batch_normalization/FusedBatchNorm:0, layer type = ( batchnorm ),
 inputs =
 Conv2d_0/Conv2D:0,
 input shapes = (1, 1, 24, 112, 112),
 outputs =
 Conv2d_0/batch_normalization/FusedBatchNorm:0,
 output shapes = (1, 1, 24, 112, 112)

```

**Comment by Mstronach** [comment]
Hi @soon-yau, this op has been added in the latest release. Please try it out and feel free to reopen this or submit a new issue if you are still experiencing issues. Thanks!
