### ISSUE TITLE
Can't convert from a .pb file

### ISSUE THREAD

**Issue by Ketsuko** [tf-coreml/tf-coreml#290]
Hey,

I'm currently trying to convert a tensforflow graph to coreml. The neural network is as a .pb file (which is associated with two other files in a folder for the varaibles and the weights).

I can load it, use it and predict from an input image on a jupyter notebook with no problems.

However, when i'm trying to convert it with:

frozen_model_file = '/Users/Desktop/mobile_net/saved_model.pb'
coreml_model_path = 'my_model.mlmodel'
coreml_model = tfcoreml.convert(
        tf_model_path=frozen_model_file,
        mlmodel_path=coreml_model_path,
        input_name_shape_dict={'image:0':[224,224,3,1]},
        output_feature_names=['descriptor:0'])

I got the following error in the convert line:

DecodeError                               Traceback (most recent call last)
<ipython-input-183-60f8cca2053c> in <module>()
      5         mlmodel_path=coreml_model_path,
      6         input_name_shape_dict={'image:0':[224,224,3,1]},
----> 7         output_feature_names=['descriptor:0'])

~/Desktop/tf-coreml/tfcoreml/_tf_coreml_converter.py in convert(tf_model_path, mlmodel_path, output_feature_names, input_name_shape_dict, image_input_names, is_bgr, red_bias, green_bias, blue_bias, gray_bias, image_scale, class_labels, predicted_feature_name, predicted_probabilities_output, add_custom_layers, custom_conversion_functions)
    591       predicted_probabilities_output=predicted_probabilities_output,
    592       add_custom_layers=add_custom_layers,
--> 593       custom_conversion_functions=custom_conversion_functions)

~/Desktop/tf-coreml/tfcoreml/_tf_coreml_converter.py in _convert_pb_to_mlmodel(tf_model_path, mlmodel_path, output_feature_names, input_name_shape_dict, image_input_names, is_bgr, red_bias, green_bias, blue_bias, gray_bias, image_scale, class_labels, predicted_feature_name, predicted_probabilities_output, add_custom_layers, custom_conversion_functions)
    148   tf.reset_default_graph()
    149   gdef = tf.GraphDef()
--> 150   gdef.ParseFromString(serialized)
    151 
    152   with tf.Graph().as_default() as g:

DecodeError: Error parsing message

Do you know what is going on?

P.S. I got the same error when I try to load the model and "parse" it with 
with tf.gfile.GFile(frozen_model_file, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())

Thank you for your help!

**Comment by lcycoding** [comment]
Hi Ketsuko,
My guess is that the `ParseFromString` only takes frozen graph pb but not saved model.
You could try convert original ckpt to frozen graph and convert it again.

**Comment by Ketsuko** [comment]
lcycoding,

Thank you for your answer! 
Yes, this is also what it feel, the probleme is, I have nockpt files. To be more precise, I juste have a variables.index and a variables.data-00000-of-00001 ... the model can be loaded and return results...

However, I have been able to  converted it to a .TFLITE

So, I'm wondering, is there a way to convert a .tflite to a .mlmodel?
I've seen somewhere on Stackoverflow to use toco, but I couldn't find a relevant docs for it...

Any thoughts?

Thanks!

**Comment by lcycoding** [comment]
@Ketsuko 
Try this script to convert savedmodel to frozen graph
Hope this helps.
```
import tensorflow as tf

with tf.Session(graph=tf.Graph()) as sess:
    tf.saved_model.loader.load(sess, ["serve"], './folder_you_save_savedmodel')
    graph = tf.get_default_graph().as_graph_def()
    with tf.gfile.GFile('./frozen.pb', "wb") as f:
        f.write(graph.SerializeToString())
```

And for your another question, TFLite file may not be compatible with mlmodel file.

**Comment by Ketsuko** [comment]
@lcycoding 
Thank you so much for your help!!!!!
It worked very fine!!!
I have now a real pb frozen graph!

**Comment by nikviradiya26** [comment]
> lcycoding,
> 
> Thank you for your answer!
> Yes, this is also what it feel, the problem is I have no ckpt files. To be more precise, I juste have a variables.index and a variables.data-00000-of-00001 file... the model can be loaded and returns results...
> 
> However, I have been able to converted it to a .TFLITE file (tensorflow lite)
> 
> So, I'm wondering, is there a way to convert a .tflite into a .mlmodel?
> I've seen somewhere on Stackoverflow toco can be used but I couldn't find a relevant doc for it...
> 
> Any thoughts?
> Hello Ketsuko,

Can you please share the script using which you converted ..data-00000-of-00001 to .TFLITE file?
Your help will really be appreciated.
> Thanks!
