### ISSUE TITLE
TensorFlow 2 support

### ISSUE THREAD

**Issue by EliotAndres** [tf-coreml/tf-coreml#294]
Is support for TensorFlow 2 planned ?

At the moment, when using `tf_converter.convert`, I get the following error:

`module 'tensorflow' has no attribute 'reset_default_graph'`

**Comment by Lisandro79** [comment]
Is this supported now?

**Comment by mats-claassen** [comment]
This issue is marked as Done and the latest release (1.1) seems to include TF 2 support. But I am still experiencing this issue. Could anyone convert a TF2 model?

**Comment by aseemw** [comment]
@mats-claassen could you please file a reproducible issue of TF 2.0 conversion not working? 
Please see this guide for a few details on TF 2.0 conversion:  https://github.com/apple/coremltools/blob/master/docs/NeuralNetworkGuide.md

**Comment by Mstronach** [comment]
Experimental support for TensorFlow 2.x and `tf.keras` was added in coremltools 3.1 with some [known issues](https://github.com/apple/coremltools/releases), could you try again with the latest version of coremltools 3.1 and/or tfcoreml 1.1. Please see the [neural network conversion guide](https://github.com/apple/coremltools/blob/master/docs/NeuralNetworkGuide.md#tensorflow-converter) and/or [Jupyter notebooks](https://github.com/tf-coreml/tf-coreml/tree/master/examples) for some conversion examples. If you encounter any issues while converting your model, please [file a new GitHub issue](https://github.com/apple/coremltools/issues/new/choose) with steps to reproduce. Thanks!

**Comment by mats-claassen** [comment]
@aseemw I could convert a model built with TensorFlow 2.0 but I had to call the `convert` function using TensorFlow 1.x. That means having two separate environments.

The error in my case comes from [line 214](https://github.com/tf-coreml/tf-coreml/blob/master/tfcoreml/_tf_coreml_converter.py#L214) of _tf_coreml_converter where it calls `tf.reset_default_graph()`.

Is it correct?

**Comment by aseemw** [comment]
There shouldn't be need for two separate environments, if you use coremltools==3.1 and tfcoreml==1.1
Did you invoke the converter with the argument `minimum_ios_deployment_target` ='13' ? 
An error reproducing script would be great.

**Comment by mats-claassen** [comment]
I did not set the `minimum_ios_deployment_target ='13'`. That is the problem. Thanks for the help

**Comment by hendriks73** [comment]
Is there a way to make this work with `minimum_ios_deployment_target ='12'` ?
I'm hoping to deploy to macOS 10.14.

**Comment by jpbalarini** [comment]
I'm facing the same problem while trying to export to iOS < 13.
I saw on `_tf_coreml_converter.py` that it tries to do:
```
tf.reset_default_graph()
gdef = tf.GraphDef()
```
instead of:
```
tf.compat.v1.reset_default_graph()
gdef = tf.compat.v1.GraphDef()
```

but even if I change that bit, I still get a:
```
Traceback (most recent call last):
  File "coreml_export.py", line 32, in <module>
    minimum_ios_deployment_target='11.2')
  File "/Users/jpb/.virtualenvs/cv37/lib/python3.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 718, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/Users/jpb/.virtualenvs/cv37/lib/python3.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 216, in _convert_pb_to_mlmodel
    gdef.ParseFromString(serialized)
google.protobuf.message.DecodeError: Error parsing message
```
