### ISSUE TITLE
model_precision='float16' 

### ISSUE THREAD

**Issue by mrgloom** [tf-coreml/tf-coreml#295]
`coremltools.converters.keras.convert` have parameter `model_precision='float16'` and seems `tfcoreml.tf_converter.convert` doesn't have this option, is there any other way to convert tensorflow model to float16 coreml model?

**Comment by aseemw** [comment]
after conversion you can always use the coremltools quantization utils to get float 16 weights model, this has the same effect as the argument in keras convert call

```
import coremltools
from coremltools.models.neural_network import quantization_utils
mlmodel_fp16 = quantization_utils.quantize_weights(mlmodel_fp32, 16)
mlmodel_fp16.save(coreml_model_path)
```

**Comment by mrgloom** [comment]
Looks like this [doc](https://apple.github.io/coremltools/generated/coremltools.models.neural_network.quantization_utils.html#coremltools.models.neural_network.quantization_utils.quantize_weights) is outdated:
`nbits – Int Number of bits per quantized weight. Only 8-bit and lower quantization is supported`

Also as I can see here linear quantization is used by default:
https://github.com/apple/coremltools/blob/2b0c00eaec53338d3539bc4009210985fc7c2477/coremltools/models/neural_network/quantization_utils.py#L879

**Comment by mrgloom** [comment]
Here is some clarification on this topic:
https://github.com/apple/coremltools/issues/316
