### ISSUE TITLE
[feature request] Supports operations of constants

### ISSUE THREAD

**Issue by y-ich** [tf-coreml/tf-coreml#300]
Hi.

Some operations require Const or Identity with Const.
For example, Transpose requires Const as perm, MatMul requires Identity with Const as the second input.

The model I tried to convert has operations such as Concat and Reshape with Const and I got errors.

I will appreciate that you will support operations of constants.

Or are there any scripts which converts operations of constants to precalculated constants?

Thank you.

**Comment by 1duo** [comment]
Hi @y-ich, as you probably already find out, we do constant propagation before the actual conversion. Is that something you're referring to? If not, could you [file a feature request](https://github.com/tf-coreml/tf-coreml/issues/new?assignees=&labels=future+feature&template=---feature-request.md&title=) with a detailed explanation of the use case. Thanks!

**Comment by y-ich** [comment]
1duo san,

"constant_propagation" in coremltools is what I wanted.
Thank you!
