### ISSUE TITLE
Using multiple CoreML instances with same architecture in multiple apps

### ISSUE THREAD

**Issue by lqhuy93** [tf-coreml/tf-coreml#302]
The non-deterministic issue appears when I run my apps parallelly (mostly for devOps and testing), which means each process creating a few CoreML instances (same architecture, but different input size). Everything is okay if I run it sequentially. So I have a couple of questions:
- Does Coreml manage nodes(tensors) by name/label? So when I load multiple instances with the same model, it produces non-deterministic results.
- Can I use 1 CoreML shared instance for multiple apps? If yes, how can I do that? 

Thanks for your work, really appreciated it.

**Comment by lqhuy93** [comment]
solved the issue, seems like my first argument is true. 
`Coreml manages tensors by label`, so if you tend to run multiple coreml models in 1 app, making sure each tensor names are unique.

**Comment by vade** [comment]
To be clear, I run multiple concurrent instances of a CoreML model in the same memory address space for my app and have no issues with prediction output (its stable, the API is object oriented), so this isn't a CoreML iOS/macOS  runtime issue but perhaps with the python runtime (Im presuming you are running inference on a CoreML model via CoreMLTools?)? It might be better suited to ask about the issue there?

**Comment by lqhuy93** [comment]
@vade ah, I was running 3 different models with the same architecture (so some nodes/tensors have the same label coincidentally), the problem was solved by adding a prefix label, made sure all node's names/labels are unique (in all models)

**Comment by guy4261** [comment]
@vade concurrent as in - only one is actually running at a time (unlike the multiprocessing setting of @lqhuy93 ?)

@lqhuy93 - can you give an example (preferably Python code :pray:) of how to do this renaming? Can it be done dynamically when you load the CoreML model, or do you have to actually compile to CoreML 3 TensorFlow models, each with a different prefix? Thanks in advance!! 🙇
