### ISSUE TITLE
I can't convert my mobileNetSSD model.

### ISSUE THREAD

**Issue by leeburt** [tf-coreml/tf-coreml#303]
Firstly,i use ssd_example.ipynb is ok. But when i change the model to my model is wrong.Here is my log [tf_convert_error_log.txt](https://github.com/tf-coreml/tf-coreml/files/3189585/tf_convert_error_log.txt).
It's my model [mobileNetSSD.zip](https://github.com/tf-coreml/tf-coreml/files/3189630/mobileNetSSD.zip).

look forward to your reply.

**Comment by 1duo** [comment]
This should be resolved in the latest `coremltools>=3.0`. Please re-open if you still encounter this issue. Thanks!
