### ISSUE TITLE
Is it support tf.keras’s model?

### ISSUE THREAD

**Issue by tucan9389** [tf-coreml/tf-coreml#305]
I have succeeded to convert pure keras model, but there are some problem with tf.keras’s model. 
Is tf-coreml support tf.keras model conversion?

Thanks

**Comment by aseemw** [comment]
Yes, if you save out the graph to a frozen .pb format.

**Comment by tucan9389** [comment]
Thanks for reply!
What about InputLayer from functional method on tf.keras?
Is it support with same way? Any advice can help me.

## Related issue
https://github.com/apple/coremltools/issues/231

**Comment by aseemw** [comment]
tf.keras is not supported currently by the keras converter (which takes as input .h5 file format), which is part of coremltools. 
However if a .pb model is saved as a frozen graphed, tfcoreml converter should be able to convert it.

**Comment by tucan9389** [comment]
I see! 
- [not support yet] tf.keras → coreml (`keras converter`)
- [support] tf.keras → frozen pb -> coreml (`tf-coreml`)

Thanks  a lot 👍
