### ISSUE TITLE
Unable to convert a Tensorflow DeepSpeech model with beta converter

### ISSUE THREAD

**Issue by MatthewWaller** [tf-coreml/tf-coreml#309]
Hello,

I recently tried converting a Tensorflow model of DeepSpeech to CoreML and was unable to. 
Here is where the pre-trained model came from: `https://github.com/mozilla/DeepSpeech/releases/download/v0.4.1/deepspeech-0.4.1-models.tar.gz`

Here is my code to convert:
```
import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = '/path/to/deep_speech.pb',
                     mlmodel_path = '/path/to/export/deepspeech_model.mlmodel',
                     output_feature_names = ['logits:0', 'new_state_c:0', 'new_state_h:0'],
                     input_name_shape_dict = { 
                         'input_reshaped:0': [16, 494],
                         'previous_state_c:0': [1,2048],
                         'previous_state_h:0': [1,2048]
                     },
                     use_coreml_3 = True)
```

Here is the end of the output:
```
68         for f in ssa.functions.values():
     69             for n in f.graph.values():
---> 70                 assert (n.datatype is not None)
     71     return ssa

AssertionError: 
```

**Comment by lauriebyrum** [comment]
+1. I'm getting this for my custom model that converts fine without the use_coreml_3 = True flag

**Comment by lauriebyrum** [comment]
(This is preventing experimentation with CoreML3, in case it isn't obvious...)

**Comment by aseemw** [comment]
If the model converts without the flag being set to true, thats great, please continue to use that. 
The flag ``use_coreml_3``, at the moment, is really for trying out the converter on those networks (such as RNN etc) that were not supported in the previous converter.

**Comment by 1duo** [comment]
@MatthewWaller @lauriebyrum Here's an example convert script: https://github.com/tf-coreml/tf-coreml/blob/master/examples/deep_speech.ipynb. Note that this convert requires seed 5 or later. Please re-open if you find any issues. Thanks!
