### ISSUE TITLE
Convert CoreML to Tensorflow

### ISSUE THREAD

**Issue by Vortec4800** [tf-coreml/tf-coreml#316]
I know this library is primarily designed to go in the other direction, but I have a trained CoreML model that I need to run in the cloud. Is there a way to configure this tool to take my CoreML model and covert it to a TF model?

**Comment by aseemw** [comment]
This repo does not go in the other direction. 
However, you could try using [onnxmltools](https://github.com/onnx/onnxmltools) to go from CoreML to ONNX format.
Then, that can be run using onnx runtime or converted to TF (https://github.com/onnx/onnx-tensorflow)

**Comment by Vortec4800** [comment]
Cool thanks for the tip, I'll give that a try and see how it works.

**Comment by fodeguirassy** [comment]
For anyone landed here, the above suggested workaround did not work for me. 
I ended up stucked in the following configuration : 

- onnxmltools does not support coremltools > 3.1
- to install coremltools <= 3.1, you need python2
- onnxtmltools cannot be used with python2

See the attached screen capture for the detailed error trace

![Screenshot 2021-07-27 at 16 46 42](https://user-images.githubusercontent.com/16901741/127175262-29740351-cf94-467d-8590-398c91e6b050.png)
