### ISSUE TITLE
NotImplementedError: Unsupported Ops of type: DepthToSpace

### ISSUE THREAD

**Issue by joacimstahl** [tf-coreml/tf-coreml#326]
Hi,

I get "NotImplementedError: Unsupported Ops of type: DepthToSpace" however when i check the source code and list of supported ops DepthToSpace is there.

**Comment by 1duo** [comment]
Hi @joacimstahl, thanks for reporting this issue. The `DepthToSpace` op has been recently added to coremltools: see https://github.com/apple/coremltools/pull/437. You can expect this fix to land in next beta release soon (`coremltoos==3.0b6`). Have a try and let us know if it does not work for you. Thanks!
