### ISSUE TITLE
Question：Why tf-coreml need this limitation 'len(tensor.shape) <= 4'?

### ISSUE THREAD

**Issue by zyx1213271098** [tf-coreml/tf-coreml#330]

**Comment by aseemw** [comment]
This is not the case if you use the newer tf-coreml converter with the beta tfcoreml and coremltools wheels: https://github.com/tf-coreml/tf-coreml#new-beta-tfcoreml-converter-with-core-ml-3

**Comment by zyx1213271098** [comment]
alright, thank you very much!
