### ISSUE TITLE
Adding metadata as author and description

### ISSUE THREAD

**Issue by Jordi100** [tf-coreml/tf-coreml#332]
Hello,

I have tried with different options to add the metadata labels.
The examples in internet are those:
```
core_model.author = 'Hincat'
core_model.license = 'BSD-3'
core_model.save('Favourite.mlmodel')

mlmodel.author = ‘tpeter’
mlmodel.license = ‘MIT’
mlmodel.short_description = ‘This model takes a picture of a leopard and predicts its gender’

model.author = 'Author'
model.license = 'BSD'
model.short_description = 'Predicts the price of a house in the Seattle area.'
```
But none of these options worked. (Obviously changing the text after the equal symbol.)
Please, can you inform about how to set the metadata?
Regards,

Jorge

**Comment by Jordi100** [comment]
Hello Aseemw,
Maybe my question was not clear.
Please, can you answer the following?
**How can I add the author and description inside a coreml file that is build from a .pb file?**
Regards,
Jorge

**Comment by vade** [comment]
You edit the core ml spec and then save the model, like so:

```
model  = coremltools.models.MLModel(path)

#get the raw spec if you want to adjust layer names
#spec = model.get_spec()
# do something with the spec
# make a new model with the spec
#model = coremltools.models.MLModel(spec)

# Set the model metadata
model.author = 'Your Name'
model.license = 'Your License'
model.short_description = 'Description'
model.versionString =  '1.0 Beta 1'
model.save(new_path)
```

**Comment by Jordi100** [comment]
Hello Vade,

Thank you for your answer.
It works, it adds the author, license and description metadata.
But the problem is that the original mlmodel file has as Type parameter:

Input  Image (Color 300 x 400)
Output Image (Color 400 x 300)

But the new mlmodel file has:
Input  Image (Color 300 x 400)
**Output MultiArray (Double 3 x 400 x 300)**

Please, why the output has changed?
Regards,

Jorge

**Comment by vade** [comment]
Did you adjust the spec at all?

**Comment by Jordi100** [comment]
If I add:

spec = mlmodel.get_spec( )
output = spec.description.output[0]

as used to create the original file, it launch and error. Do I need to specify something more?

**Comment by vade** [comment]
You shouldn't need to touch the spec

just

```model  = coremltools.models.MLModel(path)
# Set the model metadata
model.author = 'Your Name'
model.license = 'Your License'
model.short_description = 'Description'
model.versionString =  '1.0 Beta 1'
model.save(new_path)
```

without you posting code its impossible to know what is going on. Please post some code.

**Comment by Jordi100** [comment]
I have created the new file to add the metadata with the folllowing code:

import tfcoreml as tf_converter
import coremltools
model  = coremltools.models.MLModel('frozen5.mlmodel')

# Set the model metadata

model.author = 'Jorge Gregorio'

model.license = 'Do not sell'

model.short_description = 'Neural art'

model.save('frozen5b.mlmodel')

It works, but it changes the output Type as I specified before.
Regards,
Jorge

**Comment by vade** [comment]
That sounds like a bug, you can get the model spec before you change anything, print it, and what changed before and after, and try to force setting the spec values from before the change? 

Thats odd. Maybe open a new issue just for that.

**Comment by Jordi100** [comment]
Thank you Dave for your answer.
I will try what you say tomorrow. I have very few knowledge with coreml.
If It does not work I will open a new issue.
Thank you. Regards.
Jorge

**Comment by Mstronach** [comment]
This issue is being closed due to inactivity. Please feel free to re-open if you still have questions surrounding this issue. Thanks!
