### ISSUE TITLE
ValueError: output name: logits/BiasAdd, was provided, but the Tensorflow graph does not contain a tensor with this name.

### ISSUE THREAD

**Issue by abdou31** [tf-coreml/tf-coreml#337]
## System Information
- Python 3.6
- Windows 10 x64
- Tensorflow 1.14.1

I have a frozen inference model and I want it to tfcoreml model but I have got some errors when trying to get the .mlmodel file: 

>ValueError: output name: logits/BiasAdd was provided, but the Tensorflow graph does not contain a tensor with this name.

I visualize the model using Netron :

![image](https://user-images.githubusercontent.com/19480228/65243768-4e747180-dae9-11e9-8187-bd5ba48d1b7f.png)

The input and the output tensors are very clear here as you can see:

![image](https://user-images.githubusercontent.com/19480228/65243798-677d2280-dae9-11e9-83fa-c902f02ad71a.png)

![image](https://user-images.githubusercontent.com/19480228/65243811-706df400-dae9-11e9-934a-274917b84f4d.png)

And this is the code that used:

```python

import tfcoreml as tf_converter
tf_converter.convert(tf_model_path='C:\\Users\\User\\cnn-facial-landmark\\irismodel\\freeze2\\frozen_inf_model_iris.pb',
                     mlmodel_path='irismodelios.mlmodel',
                     output_feature_names=['logits/BiasAdd'],
                     input_name_shape_dict={'input_to_float': [1, 112, 112, 3]})
```

**Comment by 1duo** [comment]
Hi @abdou31, I think this is resolved as you mentioned in https://github.com/tf-coreml/tf-coreml/issues/338? Let us know if you have any further questions.

**Comment by 1duo** [comment]
Close due to inactivity. Please reopen if you still see this error. Thanks!
