### ISSUE TITLE
NotImplementedError: Unsupported Ops of type: OneShotIterator,IteratorGetNext,Shape,Pack

### ISSUE THREAD

**Issue by abdou31** [tf-coreml/tf-coreml#338]
## 🐞Describe the bug
I have a frozen inference model and I'm trying to convert this model to coreml model, but I get some errors
## Trace

>NotImplementedError: Unsupported Ops of type: OneShotIterator,IteratorGetNext,Shape,Pack

## To Reproduce

```python
import tfcoreml as tf_converter
tf_converter.convert(tf_model_path='C:\\Users\\starinfo\\cnn-facial-landmark\\irismodel\\freeze2\\frozen_inf_model_iris.pb',
                     mlmodel_path='irismodelios.mlmodel',
                     output_feature_names=['logits/BiasAdd:0'],
					 input_name_shape_dict={'input_to_float': [1, 112, 112, 3]})
```

![image](https://user-images.githubusercontent.com/19480228/65250714-4a9b1c00-daf6-11e9-9920-31e0f2a1dd0e.png)

![image](https://user-images.githubusercontent.com/19480228/65250741-5850a180-daf6-11e9-8756-89ca8fb779c4.png)

![image](https://user-images.githubusercontent.com/19480228/65250755-5dadec00-daf6-11e9-9759-d4caee6a2385.png)

## System environment (please complete the following information):
 - coremltools version  : ( I installed it via command `pip3 install coremltools`)
 - tf-coreml version: 0.4.0b1
 - tensorflow version (e.g. 1.14): 1.14
 - OS (e.g., MacOS, Linux): Windows 10 x64
 - macOS version (if applicable):
 - How you install python (anaconda, virtualenv, system): system
 - python version (e.g. 3.7): 3.6

**Comment by 1duo** [comment]
Hi @abdou31, thanks for reporting issue! Could you try `pip3 install coremltools==3.0b6` and:

```
import tfcoreml as tf_converter
tf_converter.convert(tf_model_path='model.pb',
                                    mlmodel_path='irismodelios.mlmodel',
                                    output_feature_names=['logits/BiasAdd'],
			            input_name_shape_dict={'input_to_float': [1, 112, 112, 3]},
                                    use_coreml_3=True)
```

Note: that this `use_coreml_3=True` flag is temporary due to beta converter. The behavior might be updated in the 3.0 release.

**Comment by abdou31** [comment]
Thanks for your answer, 
I have tried executing the command `python3 conver_cml.py` after installing `coremltools` , I get this error:
>  File "C:\Users\st****\AppData\Local\Programs\Python\Python36\lib\site-packages\coremltools\converters\nnssa\frontend\tensorflow\parse.py", line 133, in parse_attr
    raise NotImplementedError("func not yet implemented")
NotImplementedError: func not yet implemented

**Comment by 1duo** [comment]
> Thanks for your answer,
> I have tried executing the command `python3 conver_cml.py` after installing `coremltools` , I get this error:
> 
> > File "C:\Users\st****\AppData\Local\Programs\Python\Python36\lib\site-packages\coremltools\converters\nnssa\frontend\tensorflow\parse.py", line 133, in parse_attr
> > raise NotImplementedError("func not yet implemented")
> > NotImplementedError: func not yet implemented

Could you share the model and conversion script so that we could reproduce in our side? Thanks!

**Comment by abdou31** [comment]
The conversation script is what you write I just copied what you write.
For the model, I just uploaded the image that show the architecture.
Do you want to upload the model file ( .pb ) in the github?

**Comment by 1duo** [comment]
@abdou31 The model (`.pb`) file and the conversion scripts are extremely helpful for Core ML developers to reproduce and diagnose the issue. So it'd be great if you can share that. If it's a publically available model, you can just give us a pointer, otherwise, you can upload it to the Apple Bug Report system.

**Comment by abdou31** [comment]
Thanks for your help, I have solved my problem by optimizing the frozen graph model and eliminating Unuspported Ops [Stackoverflow solution](https://stackoverflow.com/questions/48117854/how-to-use-a-retrained-tensorflow-for-poets-graph-on-ios)

**Comment by 1duo** [comment]
@abdou31 Awesome! That's also usually recommended for better performance.
