### ISSUE TITLE
Is it possible to change the type of the input tensor in the coreml model from multiarray to image?

### ISSUE THREAD

**Issue by abdou31** [tf-coreml/tf-coreml#339]
## System Information
- Mac OS ( for testing the project) & Windows 10 x64
- python 3.6
- Tensorflow 1.14.1

+ I have a coreml model with those parameters and I want to change the type of the input tensor from Multiarray with shapes (112,112,3) to RGB image(112,112)

>Core ML input(s):
[name: "input_to_float__0"
type {
multiArrayType {
shape: 3
shape: 112
shape: 112
dataType: DOUBLE
}
}
]
Core ML output(s):
[name: "logits__BiasAdd__0"
type {
multiArrayType {
shape: 80
dataType: DOUBLE
} 
}
]

![image](https://user-images.githubusercontent.com/19480228/65515961-6c264a00-dee0-11e9-8335-343c9f546447.png)

Is it possible to do that?
How can I do that?

**Comment by aseemw** [comment]
Yes, please examples: https://github.com/tf-coreml/tf-coreml/blob/master/examples/inception_v1_preprocessing_steps.ipynb and https://github.com/tf-coreml/tf-coreml/blob/master/examples/style_transfer_example.ipynb

**Comment by abdou31** [comment]
Thanks,
I solved my problem and I used this script : 
```python
coreml_model = tfcoreml.convert(
        tf_model_path=tf_model_path,
        mlmodel_path=coreml_model_file,
        input_name_shape_dict=input_tensor_shapes,
        output_feature_names=output_tensor_names,
        image_input_names = image_input_name,
        class_labels = class_labels,
        red_bias = -1,
        green_bias = -1,
        blue_bias = -1,
     # image_scale = 2.0/255.0)  
```

I comment the last line because when I use it, the model gives me false predictions
