### ISSUE TITLE
Pre-processing parameters not added

### ISSUE THREAD

**Issue by manuelcosta74** [tf-coreml/tf-coreml#340]
## ❓I'm trying to use tf-coreml to convert a model, but it seams that pre-processing parameters are not being added. Any ideia why?

scale = 1.0 / 128.0

coreml_model = tfcoreml.convert (tf_model_path=tf_model_path,
                                 mlmodel_path=coreml_model_file,
                                 input_name_shape_dict={"img_inputs:0": [1, 112, 112, 3]}, # batch size is 1
                                 output_feature_names= ['embeddings:0'],
                                 image_input_names = ['img_inputs:0'],
                                 red_bias    = - 127.5 * scale,
                                 green_bias  = - 127.5 * scale,
                                 blue_bias   = - 127.5 * scale,
                                 image_scale = scale,
                                 use_coreml_3= False)

spec = coreml_model.get_spec()

nn_spec = spec.neuralNetwork

pprint(dir(nn_spec.preprocessing))

Printing seems to be empty.

**Comment by aseemw** [comment]
Not sure, the call pattern looks correct. 
`image_input_names` is not yet supported with `use_coreml_3= True`, which should be added soon. However, that flag is false in this case. 

Is this model specific? For instance when you run the examples in https://github.com/tf-coreml/tf-coreml/tree/master/examples which have image pre-processing conversions, do you still see the issue?

**Comment by manuelcosta74** [comment]
Hi @aseemw 

i did answer yesterday, but don't know what happened and the message was not filed.
Converter is working and a Scalar node is added after the input with the correct parameters. I was just confused by pprint(dir(nn_spec.preprocessing)) that did not print any values. 
Another doubt that we have is to change the input name.
We tried the following

input = spec.description.input[0]
input.name = 'image'

When coremltools.utils.save_spec is called we do have a warning saying that the model will not run. It seems that parameters will have some mapping based on image_input_names initially specified.
How change the name when pre-processing parameters were specified?

pprint(dir(nn_spec.preprocessing))  - output

['MergeFrom',
 '__class__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'add',
 'append',
 'extend',
 'insert',
 'pop',
 'remove',
 'sort']

**Comment by aseemw** [comment]
Regarding the pre-processing params, maybe this will help: https://github.com/apple/coremltools/blob/master/docs/APIExamples.md#printing-the-pre-processing-parameters


Regarding changing the name of the input, 
apart from changing it in `spec.description`, you would also need to iterate over the layers and change it where ever its being used as an input,

That is, once `nn_spec` is obtained as discussed in the link above,
```
for layer in nn_spec.layers:
    for i, inp_ in enumerate(layer.input):
         if inp_ == old_name: #whatever the old input name is
              layer.input[i] = new_name #whatever the new desired input name is
```

**Comment by manuelcosta74** [comment]
@aseemw  did try it before

and the graph seems ok in Netron. The name is changed. 
Printing the parameters after changing the name produces this, though.

[featureName: "img_inputs__0"
scaler {
  channelScale: 0.0078125
  blueBias: -0.99609375
  greenBias: -0.99609375
  redBias: -0.99609375
}
]

Source code

```
import tfcoreml
import coremltools
import copy
import tensorflow as tf

from coremltools.proto import FeatureTypes_pb2 as ft
from  coremltools.models.neural_network.printer import print_network_spec

# TF graph definition
#tf_model_path = 'MobileFaceNet_9925_9680.pb'
tf_model_path = 'FaceMobileNet192_train_false.pb' #https://github.com/sirius-ai/MobileFaceNet_TF/files/3551493/FaceMobileNet192_train_false.zip

# Output CoreML model path
coreml_model_file = 'MobileFaceNet_9925_9680.mlmodel'
 
# Scale used is based on data pre-processing code that is scaling images with fixed values
# https://github.com/sirius-ai/MobileFaceNet_TF/blob/master/utils/data_process.py (line 120 and 121)
# img = img - 127.5
# img = img * 0.0078125

scale = 1.0 / 128.0

coreml_model = tfcoreml.convert (tf_model_path=tf_model_path,
                                 mlmodel_path=coreml_model_file,
                                 input_name_shape_dict={"img_inputs:0": [1, 112, 112, 3]}, # batch size is 1
                                 image_input_names = ['img_inputs:0'],
                                 output_feature_names= ['embeddings:0'],
                                 red_bias    = - 127.5 * scale,
                                 green_bias  = - 127.5 * scale,
                                 blue_bias   = - 127.5 * scale,
                                 image_scale = scale,
                                 use_coreml_3= False)


spec = coreml_model.get_spec()

nn_spec = spec.neuralNetwork


print("####### 1 #######")
print(nn_spec.preprocessing)

input = spec.description.input[0]
output = spec.description.output[0]

input.type.imageType.colorSpace = ft.ImageFeatureType.ColorSpace.Value('RGB')


input.type.imageType.width = 112  
input.type.imageType.height = 112


# get NN portion of the spec
nn_spec = spec.neuralNetwork

old_name = input.name
input.name = 'image'
output.name = 'output'

for layer in nn_spec.layers:
    for i, inp_ in enumerate(layer.input):
         if inp_ == old_name: #whatever the old input name is
             print("Layer name changed from  " + inp_ + " to " + input.name)
             layer.input[i] = input.name #whatever the new desired input name is
              
#nn_spec.layers[0].input[0] = 'image'
nn_spec.layers[len(nn_spec.layers)-1].output[0] = 'output'

nn_spec.layers[len(nn_spec.layers)-1].output[0] = 'embeddings_raw'
embeddings_norm_layer = nn_spec.layers.add()
embeddings_norm_layer.name = 'embeddings_norm_layer'
embeddings_norm_layer.input.append('embeddings_raw')
embeddings_norm_layer.output.append('output')

params =  embeddings_norm_layer.l2normalize
params.epsilon = 1e-6

coreml_model = coremltools.models.MLModel(spec)
spec = coreml_model.get_spec()

nn_spec = spec.neuralNetwork

print("####### 2 #######")
print(nn_spec.preprocessing)

coremltools.utils.save_spec(spec, 'MobileFaceNet.mlmodel')
```

**Comment by 1duo** [comment]
Hi @manuelcosta74, we've recently added support for pre-processing parameters in https://github.com/tf-coreml/tf-coreml/pull/344/files, could you try with the `target_ios='13'` flag? Thanks!

**Comment by aseemw** [comment]
Please re-open if the issue is still not resolved.
