### ISSUE TITLE
Convert LSTM. ValueError: Graph has cycles. 

### ISSUE THREAD

**Issue by LinShihChieh** [tf-coreml/tf-coreml#361]
When I trying to convert LSTM from tensorflow to coreml,  and I get the error: "ValueError: Graph has cycles."

Using the neural network builder API provided by coremltools. 
Is it the only way to convert rnn model or any graph has cycles?

How to abstract the weight matrices and bias vectors from pre-trained model from tensorflow(.pb)

**Comment by aseemw** [comment]
Please use the flag `minimum_ios_deployment_target = '13'` as shown [here](https://github.com/apple/coremltools/blob/master/docs/NeuralNetworkGuide.md#tensorflow-1-converter)

**Comment by aseemw** [comment]
Please re-open with a reproducible script if the the issue still persists with the latest tfcoreml and coremltools packages.
