### ISSUE TITLE
AddV2 operation is still not supported but upgrade version says it is!

### ISSUE THREAD

**Issue by Praveenk8051** [tf-coreml/tf-coreml#367]
## 🐞Describe the bug
The AddV2 tf.operation will be present when retraining with tensorflow 2.0.0. The .pb file when converted into coreml model throws error saying  'Unsupported Ops of type: AddV2' . The upgraded version says it supports AddV2 but it does not.
https://github.com/tf-coreml/tf-coreml/releases/tag/1.1.0

## Trace
The tracing shows that the layer AddV2 operation is not added and testing is not done 
https://github.com/tf-coreml/tf-coreml/blob/master/tfcoreml/_ops_to_layers.py

## To Reproduce
Retrain mobilenet architecture using tensorflow 2.0.0 version and convert the trained model(.pb file) same to coreml model using 1.1.0
```


## System environment (please complete the following information):
 - coremltools version  (e.g., 3.0b5): 1.1.0
 - tensorflow version (e.g. 1.14): 2.0.0
 - macOS version (if applicable): 10.14.6
 - python version (e.g. 3.7): 3.7


## Additional context
https://stackoverflow.com/questions/59266844/tensorflow-pb-file-to-coreml-model-unsupported-ops-of-type-addv2

**Comment by DawerG** [comment]
The file you are referencing gets used in the old tf-coreml converter path. 

Please use the `minimum_ios_deployment_target = "13" ` to leverage the new path. The upgraded version does support AddV2 operation as it can be seen here: https://github.com/apple/coremltools/blob/891ae71a4553204ba72751c7ff67caf7aac4bf77/coremltools/converters/nnssa/coreml/ssa_converter.py#L337
