### ISSUE TITLE
No op named DecodeWav in defined operations

### ISSUE THREAD

**Issue by slin07** [tf-coreml/tf-coreml#37]
While trying the "Simple Speech Recognition" frozen graph given in this link: 
https://storage.googleapis.com/download.tensorflow.org/models/speech_commands_v0.01.zip

The TF model fails to load in tensorflow. Here's the output:
`ValueError: No op named DecodeWav in defined operations.`

I'm using TensorFlow 1.3.

**Comment by Fatlog** [comment]
Hi,

I'm new to this (so apologies!) but am I now able to convert the TF speech_data example whilst keeping the DecodeWav op? Some of the comments above seem to suggest it is now a supported op?
