### ISSUE TITLE
Issue Converting TensorFlow Model to Core ML Model

### ISSUE THREAD

**Issue by azamsharp** [tf-coreml/tf-coreml#80]
I am running the following commands and getting this result. 

<img width="651" alt="screen shot 2017-12-07 at 8 29 52 pm" src="https://user-images.githubusercontent.com/16604/33748691-8e6d8e6c-db8f-11e7-97d5-85faa41e1c55.png">

**Comment by aseemw** [comment]
This is happening because there is no tensor named "softmax:0" (provided output feature name) in the TF graph.

**Comment by azamsharp** [comment]
Thanks Aseem! So what will be the correct syntax for converting TensorFlow model to Core ML model.

**Comment by aseemw** [comment]
The syntax to call the converter is correct. You just need to find the correct name of the output tensor in your TF graph and use it in your function call. 

You could either get it form the training script you used or you can try using the script "utils/inspect_pb.py" in this repo which prints a text summary of the TF graph (all tensor names). You can also use tensorboard to visualize the graph which can help you in finding the output name ("utils/visualize_pb.py").

**Comment by azamsharp** [comment]
Thanks! I am able to generate the text summary file but I am still unsure what represents the TF graph and what I am supposed to put in output_feature_names. Here is the screenshot of the text summary file: 

<img width="771" alt="screen shot 2017-12-08 at 2 49 52 pm" src="https://user-images.githubusercontent.com/16604/33784636-39547a06-dc27-11e7-9dbf-431752e362b5.png">

**Comment by azamsharp** [comment]
I also tried to visualize the graph but the visualize is just stuck and not doing anything. As shown in the screenshot below: 
<img width="593" alt="screen shot 2017-12-08 at 2 58 13 pm" src="https://user-images.githubusercontent.com/16604/33784927-629abbea-dc28-11e7-83fe-e1d60cf15020.png">

**Comment by aseemw** [comment]
You have to open up the link in a web browser (in this case http://Mohammads-MBP.localdomain:6006) to visualize. 
The output you need depends on which tensor you want from the graph. If you scroll down towards the end of the text file, you should see the tensors towards the end of the graph (nodes close to the sink node of the graph). Maybe you want the output of the Softmax op at the end.

**Comment by azamsharp** [comment]
I opened that link and there is nothing there. Take a look at the following screenshot below: 

<img width="1063" alt="screen shot 2017-12-08 at 6 53 24 pm" src="https://user-images.githubusercontent.com/16604/33792180-9eaaf664-dc5e-11e7-8bc2-d0dd307491a1.png">

**Comment by azamsharp** [comment]
Also, the summary text file contain the following at the end of the file: 

<img width="599" alt="screen shot 2017-12-08 at 9 28 15 pm" src="https://user-images.githubusercontent.com/16604/33792187-cc682626-dc5e-11e7-9728-a0e12d9445c1.png">

**Comment by aseemw** [comment]
Okay maybe I was not clear in my earlier explanation. The text file lists all the ops present in the TF graph and numbers them 1, 2, 3 etc. At the end of the file these are just the histogram counts of the ops. 

For each op the following are listed:
- op name
- op type 
- input names and shapes
- output names and shapes

Ignore the histogram op counts at the end of the file. Instead look at the last few op descriptions. Search for the 
"op type = ( Softmax )".  For that op find the output name. Remove the "import/" from that name. That is the name of the Tensor that you are interested in and that you should pass to the converter.

**Comment by azamsharp** [comment]
Thank you so much for your continued help! I was able to convert the model to Core ML. One thing I realized is that for Core ML input parameters for the model is a multi dimensional array of Doubles. I was expected it to take an image of 244 X 244 size so it can process the image and give me predictions. I am using the Inception V1 model located at (https://storage.googleapis.com/download.tensorflow.org/models/inception_v1_2016_08_28_frozen.pb.tar.gz) 

Thanks again

**Comment by aseemw** [comment]
Great! 
You can find the description of the convert function arguments at the end of the file "tfcoreml/_tf_coreml_converter.py". In particular, argument "image_input_names" can be used to mark inputs as images. In the inception model screenshot you attached, the input name would be "input:0" (output of the op type Placeholder). You can also provide image biases and scales as additional arguments.

**Comment by lahayeg** [comment]
Thanks @aseemw, your explanation make it work for me

**Comment by devajith** [comment]
`import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'output_graph.pb',
                     mlmodel_path = 'my_model.mlmodel',
                     output_feature_names = ['final_result:0'],
                     class_labels = 'output_labels.txt',
                     image_input_names = ['input:0 : (1, 224, 224, 3)'] )`
is this script correct ?

**Comment by devajith** [comment]
is this the correct syntax : 
`
import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'output_graph.pb',
                     mlmodel_path = 'MyModel.mlmodel',
                     output_feature_names = ['final_result:0'],
                     class_labels = 'output_labels.txt',
                     image_input_names = ['input:0'] )


`

**Comment by devajith** [comment]
is this correct ?
`import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'output_graph.pb',
                     mlmodel_path = 'MyModel.mlmodel',
                     output_feature_names = ['final_result:0'],
                     class_labels = 'output_labels.txt',
                     image_input_names = ['input:0'] )`

**Comment by devajith** [comment]
is this correct code ?
import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'output_graph.pb',
                     mlmodel_path = 'MyModel.mlmodel',
                     output_feature_names = ['final_result:0'],
                     class_labels = 'output_labels.txt',
                     image_input_names = ['input:0'] )

**Comment by azamsharp** [comment]
Here is what my final script looks like: 

import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'inception_v1_2016_08_28_frozen.pb',
                     mlmodel_path = 'my_model.mlmodel',
                     output_feature_names = ['InceptionV1/Logits/Predictions/Softmax:0'],
                     image_input_names = ['input:0'])


It does produce a Core ML model but that model does not look correct. The model is missing the labels in the prediction and class labels also. 

Is there a complete example available from Google where they show how to convert a TensorFlow model to a Core ML model and then import that model into Xcode and then also show how to use it. I can import the generated model but the model does not have any class labels or anything that I can use.

**Comment by azamsharp** [comment]
Here is the error I get if I try to add class_labels. 

<img width="872" alt="screen shot 2017-12-15 at 8 51 48 am" src="https://user-images.githubusercontent.com/16604/34047257-4ef11984-e175-11e7-93e5-3942b14be66a.png">

**Comment by devajith** [comment]
i guess i got the same error, but when i updated the code base for tfcoreml its gone. Please check the closed issues : KeyError: u'classLabel' setting class_labels

**Comment by devajith** [comment]
im using following script 

   import tfcoreml as tf_converter
   tf_converter.convert(tf_model_path = 'output_graph.pb',
                     mlmodel_path = 'MyModel.mlmodel',
                     output_feature_names = ['final_result:0'],
                     class_labels = 'output_labels.txt',
                     image_input_names = ['input:0'],
                     image_scale=2/224.0, red_bias=-1, green_bias=-1, blue_bias=-1
                     )

Do you know how to add 'classLabelProbs' in output

**Comment by aseemw** [comment]
I think you should be able to use "predicted_probabilities_output" argument. Kindly see the description of all the arguments at the end of the file https://github.com/tf-coreml/tf-coreml/blob/master/tfcoreml/_tf_coreml_converter.py

**Comment by devajith** [comment]
I just tried converting below model 
https://github.com/vanhuyz/CycleGAN-TensorFlow/releases/download/v0.1-alpha/apple2orange.pb
But show error as 'ValueError: Graph has cycles.'

**Comment by aseemw** [comment]
@devajith Yes this is happening because the TF graph has cycles. CoreML supports only acyclic graphs. Recurrent nodes have a high level acyclic representation in CoreML, unlike TF.

Currently, the converter has these [limitations](https://github.com/tf-coreml/tf-coreml#limitations)). 

Most of the times the cycles are part of some kind of recurrent operation. Hopefully in the future the converter will be updated to recognize this patterns and map them to the high level CoreML abstraction. 
For now, I'd advise you to look at this [example](https://github.com/tf-coreml/tf-coreml/blob/master/examples/ssd_example.ipynb). The idea is that if you have a TF graph with cycles, you can use the graph transform tool utilities to extract acyclic subgraphs and convert those to CoreML.

**Comment by devajith** [comment]
@aseemw which transform tool utilities i need to use ? i could not figure out which part of that example is doing the extraction of the acyclic subgraph.? can you help

**Comment by aseemw** [comment]
In the example there is this function call to "strip_unused_lib.strip_unused()". Two of the arguments to that function call are "input_node_names" and "output_node_names". After this call only the subgraph starting at "input_node_names" and ending at "output_node_names" is preserved. 

You might need to analyze the graph a bit before you decide which sub graph to extract. Tensorboard is a good option to visualize the TF graph.

**Comment by devajith** [comment]
![screen shot 2017-12-27 at 1 09 36 pm](https://user-images.githubusercontent.com/9593328/34375078-bd47d50a-eb0a-11e7-8f99-942cafb4e6e0.png)

Do i need to remove the subgraph 'F' to remove the cyclic issue ?

The code i used for extraction is given below :

import urllib, os, sys, zipfile
from os.path import dirname
import numpy as np
import tensorflow as tf
from tensorflow.core.framework import graph_pb2


tf_model_path = 'orange2apple.pb'
with open(tf_model_path, 'rb') as f:
    serialized = f.read()
tf.reset_default_graph()
original_gdef = tf.GraphDef()
original_gdef.ParseFromString(serialized)

with tf.Graph().as_default() as g:
    tf.import_graph_def(original_gdef, name='')

from tensorflow.python.tools import strip_unused_lib
from tensorflow.python.framework import dtypes
from tensorflow.python.platform import gfile
input_node_names = ['ExpandDims']
output_node_names = ['output_image']
gdef = strip_unused_lib.strip_unused(
                                     input_graph_def = original_gdef,
                                     input_node_names = input_node_names,
                                     output_node_names = output_node_names,
                                     placeholder_type_enum = dtypes.float32.as_datatype_enum)
# Save the feature extractor to an output file
frozen_model_file = 'test.pb'
with gfile.GFile(frozen_model_file, "wb") as f:
    f.write(gdef.SerializeToString())

**Comment by slin07** [comment]
Hi, @devajith, 
The cycle is in the `map_4` subgraph. There is a `while` loop inside it.

**Comment by devajith** [comment]
can i strip that. ? is it going to affect the working of that model.?

**Comment by slin07** [comment]
I don't think you're able to strip it. TensorFlow has control flow ops like `map` and `while` to change the graph execution path depending on variables; CoreML on the other hand does not have support of such ops.

**Comment by noorhashem** [comment]
@aseemw  I am using a custom trained faster rcnn inception v2 model ,when i am converting to coreml, should my output feature names be the last op i have in my my model summary? or the value of the last softmax layer i find? 
this is the end of my model summary.
![screenshot from 2018-05-02 00-56-30](https://user-images.githubusercontent.com/11700198/39497572-3ac8c2d6-4da4-11e8-9c46-359bf3c26d24.png)

**Comment by noorhashem** [comment]
[text_summary.txt](https://github.com/tf-coreml/tf-coreml/files/1965494/text_summary.txt)
 this is my model summary

**Comment by noorhashem** [comment]
@aseemw i get this error 
![screenshot from 2018-05-02 02-01-02](https://user-images.githubusercontent.com/11700198/39499184-b1df77fe-4dac-11e8-9f22-a70f40be7637.png)

I checked this link : https://hackernoon.com/integrating-tensorflow-model-in-an-ios-app-cecf30b9068d

**Comment by mbenami** [comment]
Hi @noorhashem 
any luck on converting the faster rcnn model?

**Comment by BIOTONIC** [comment]
Hi @noorhashem 
I also want to convert the faster rcnn but get 'Graph has cycles' error.

**Comment by iamasimkhan** [comment]
@azamsharp 
@aseemw 
I'm using https://github.com/azamsharp/TensorFlowToCoreML. 
But the Model I created is a Model that was once created with Tensorflow. But it's not in the frozen form. Please tell me how would I convert the Object Detection API Model to .mlmodel.

**Comment by noorhashem** [comment]
@mbenami no and i used tensorflow for iOS instead

**Comment by noorhashem** [comment]
@azamsharp  Thank you, I'll check this one, also check tensorflowLite for iOS if you can manage to convert the model to .lite format and deploy it on iOS instead of the .mlmodel.

**Comment by devajith** [comment]
is it possible to convert TF graph with cycles using coreml3 ?
