### ISSUE TITLE
Class Labels Not Working 

### ISSUE THREAD

**Issue by azamsharp** [tf-coreml/tf-coreml#89]
<img width="872" alt="screen shot 2017-12-15 at 8 51 48 am" src="https://user-images.githubusercontent.com/16604/34047277-5f91d6ac-e175-11e7-88cf-21e57530a74a.png">

**Comment by aseemw** [comment]
Hi @azamsharp , you can update your local tfcoreml installation by doing: 
- pip uninstall tfcoreml (this will uninstall the pypi version)
- update your Git clone of tfcoreml repo to the latest master
- then follow the instructions here: https://github.com/tf-coreml/tf-coreml#install-from-source

This will be equivalent to having a pip package that would point to the local folder on your system (which will have the latest changes).

Kindly, let us know if you still see this bug after doing that. Thank you.

**Comment by slin07** [comment]
Thanks @aseemw for pointing out the solution. I'm able to convert the TensorFlow Inception V1 in question to CoreML with the script from @azamsharp. 
This is probably a duplicate to issue #85 .

**Comment by azamsharp** [comment]
I upgraded tfcoreml tools to the latest version and I am still seeing the same issue.

**Comment by aseemw** [comment]
Hi @azamsharp ,
@devajith (who commented in issue#80 thread), myself and @slin07 have all tried the script whose snapshot you have posted above and it is working for all 3 of us using the latest master of tfcoreml. 
Kindly check again that your repo is synced with the latest tfcoreml repo.

**Comment by azamsharp** [comment]
Hi AseemW: Thank you so much again! Yes I got it working with your help. Once, I build it from source it was working as expected! THANK YOU SO MUCH for your continuous help and support. Thank you again :)
