### ISSUE TITLE
Could not find a version that satisfies the requirement coremltools>=0.6.3 (from tfcoreml==0.1.0) (from versions: ) No matching distribution found for coremltools>=0.6.3 (from tfcoreml==0.1.0)

### ISSUE THREAD

**Issue by dhc1256436519** [tf-coreml/tf-coreml#93]
Could not find a version that satisfies the requirement coremltools>=0.6.3 (from tfcoreml==0.1.0) (from versions: )
No matching distribution found for coremltools>=0.6.3 (from tfcoreml==0.1.0)
What do this happen?

**Comment by aseemw** [comment]
Can you give a bit more specific details as to what steps you followed that led to this error?

**Comment by slin07** [comment]
Are you using virtual environment? 
Have you tried uninstalling coremltools and tfcoreml and reinstall them back?

**Comment by aseemw** [comment]
@dhc1256436519 , Kindly reopen an issue when you have more info on this problem.
