### ISSUE TITLE
Label not taken in account

### ISSUE THREAD

**Issue by Kishwar** [tf-coreml/tf-coreml#96]
After converting from tensorflow to coreml file I found that tensorflow labels are not take in account. While running model on xcode for iOS app, code returns because VNClassificationObservation not found. 

Do we have some special method to handle it unlike provide models on developers.apple.com?

best regards,
Kishwar

**Comment by slin07** [comment]
Hi, @Kishwar, are you installing from PyPI package or installing from this repo? We've fixed a similar bug recently in the repo but haven't updated the PyPI package yet. Can you try re-installing the package by doing `pip install -e .` on the repo? Thanks!

**Comment by Kishwar** [comment]
Hello Allen,

I have installed from you repo using (pip install -e .) command.

I have run /examples/inception_v3.ipynb which generates following 3 files
- tensorflow_inception_graph.pb
- imagenet_comp_graph_label_strings.txt
- inception_v3.pb

Now what I have understood from the code book that label file (imagenet_comp_graph_label_strings.txt) is never used. With my limited experience I believe .pb doesn't have label information. How does output file inception_v3.mlmodel get labels?

-- Output from mlmodel available on developer.apple.com (Resnet50)
[<VNClassificationObservation: 0x1c023a3c0> 0AB9E50B-C47D-42F3-B18E-3F82B02E4990 0.0801214 "spotlight, spot" (0.080121), <VNClassificationObservation: 0x1c0233a40> 6609D9F7-8950-4261-9E46-5CCC9C5B9E9B 0.0378467 "lighter, light, igniter, ignitor" (0.037847), ... 

We can see that output is < VNClassificationObservation ...> <Apple Identifier> <LABEL> <CONFI>

-- Output from mlmodel generated by /examples/inception_v3.ipynb
[<VNCoreMLFeatureValueObservation: 0x1c003a960> 9F47D493-AB18-4233-BCAC-52C5032B8A38 1 "MultiArray : Double 1008 vector
[-1.1015625,0.36279296875,-0.489013671875,-0.1412353515625,-1.1513671875,-0.52294921875,-1.771484375,-0.44580078125,1.6630859375,-1.0244140625,0.204833984375,-0.75146484375,-0.5234375,-1.2763671875,-2.126953125,-0.2325439453125,0.9111328125,-0.4267578125,-0.9072265625,-1.0966796875,0.86279296875,-1.8193359375,-0.85009765625,-1.0517578125,-1.2880859375,0.4228515625,-0.61328125,-0...

There is no label information. Do I need to change the code in iOS app? 

Thanks and Best regards,

**Comment by aseemw** [comment]
During conversion if you provide the "class_labels" argument, then the mlmodel file will have the label information. See /examplesinception_v1_preprocessing_steps.ipynb

**Comment by Kishwar** [comment]
Thanks Aseem, It is showing result now :)
