### ISSUE TITLE
Unsupported Ops of type: PlaceholderWithDefault

### ISSUE THREAD

**Issue by sieuwe1** [tf-coreml/tf-coreml#99]
Hello

I am having this error message:

`dyld: warning, LC_RPATH $ORIGIN/../../_solib_darwin_x86_64/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so being ignored in restricted program because it is a relative path
2018-01-04 19:47:30.977648: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX
Traceback (most recent call last):
  File "co.py", line 15, in <module>
    image_scale = 2.0/255.0)
  File "/Library/Python/2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 478, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "/Library/Python/2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 143, in _convert_pb_to_mlmodel
    _check_unsupported_ops(OPS, output_feature_names)
  File "/Library/Python/2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 111, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported Ops of type: PlaceholderWithDefault`

When i am trying to convert a tensorflow model i trained with tensorflow for poets to a CoreML model. I am using this as python code:

`import tfcoreml as tf_converter

tf_model_path = "retrained_graph.pb"
mlmodel_path = "mobilenet_v1_1.0_224.mlmodel"

mlmodel = tf_converter.convert(
                                   tf_model_path = tf_model_path,
                                   mlmodel_path = mlmodel_path,
                                   output_feature_names = ["MobilenetV1/Predictions/Softmax:0"],
                                   input_name_shape_dict = {"input:0":[1,224,224,3]},
                                   image_input_names = ["input:0"],
                                   red_bias = -1,
                                   green_bias = -1,
                                   blue_bias = -1,
                                   image_scale = 2.0/255.0)
`

Machine: mac OS Sierra 

Hope you can help me. 

Greetings Sieuwe

**Comment by nivim** [comment]
Had the same issue, you will need to **uninstall** the current package and reinstall from source (not from pip) - the explanations are at the readme file.

**Comment by iCappsCedric** [comment]
installing it that way as you said, did not fix the issue
